import type { PremiumTypeData } from '../premiumTypeData';

export const ENFJ: PremiumTypeData = {
  code: "ENFJ",
  name: "The Guide",
  tagline: "Mentoring someone and watching them flourish beyond expectations",
  accentColor: "hsl(170 60% 42%)",
  traits: ["Extraverted", "Intuitive", "Feeling", "Judging"],
  famousQuote: { text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", person: "Often attributed to mentors of the ENFJ mold" },
  introduction: [
    "ENFJs are the natural mentors of the type world — warm, articulate, and unusually skilled at seeing the potential in other people. They live to bring out the best in those around them and often shape whole communities through sustained care.",
    "ENFJs approach life through connection and purpose. They read a room faster than almost any other type, adjust to serve it, and build trust quickly. Beneath the warmth is a clear set of values they will not compromise on.",
    "ENFJs focus on future possibility, especially in people. They see who a student, colleague, or friend is becoming and gently hold the space for that becoming. They tend to be empathic, inspiring, decisive about values, and quietly ambitious.",
    "ENFJs are usually excellent teachers, leaders, and facilitators because they can align groups around a shared vision without flattening individuals. They combine the heart of a counsellor with the push of a coach.",
    "Because ENFJs are so attuned to others, they can lose track of themselves. They may say yes when they meant no, give until they are empty, and keep performing warmth long after they needed rest. Learning to protect their own inner life is their central growth task.",
    "Others see ENFJs as charismatic, caring, expressive, and remarkably put-together. Inside their trusted circle they are warm, playful, and deeply loyal. They take their roles — mentor, partner, friend — seriously and invest heavily in the people who matter to them.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Extraverted Feeling", abbr: "Fe", description: "Your primary mode. You read group feeling, social dynamics, and emotional undertones almost automatically. Your gift is harmonising and elevating the people around you." },
    auxiliary: { name: "Introverted Intuition", abbr: "Ni", description: "Your support system. You see the long arc — where a person, team, or organisation is heading. This is what turns your warmth into real vision rather than sentimentality." },
    tertiary: { name: "Extraverted Sensing", abbr: "Se", description: "Developing with age. Over time you enjoy the immediate physical present more — travel, food, sport, spontaneity. It balances your future-orientation." },
    inferior: { name: "Introverted Thinking", abbr: "Ti", description: "Your hidden edge and stress trigger. Pure, cold analysis is not your home. Under heavy stress, you may overthink, obsess over logical details, or suddenly distrust your usually strong people-reading." },
  },
  strengths: [
    { title: "People-Reading", description: "ENFJs perceive emotional undercurrents and unspoken dynamics with unusual accuracy. They know what a group needs before the group knows." },
    { title: "Inspiring Communication", description: "They can make a shared vision feel urgent, hopeful, and personal. Their speeches, emails, and one-to-ones pull people forward." },
    { title: "Mentorship", description: "They see potential and hold the space for it. Many ENFJs can point to a trail of colleagues and mentees whose lives changed because of them." },
    { title: "Decisive Commitment", description: "When an ENFJ has decided the right path, they move. They are not paralysed by endless options — they pick and then work to make it right." },
    { title: "Building Community", description: "They create cohesive, trusting groups wherever they land. Teams, families, and organisations run better with an ENFJ in them." },
    { title: "Empathic Courage", description: "They will have the hard conversation in service of the person they care about. Their care is neither sentimental nor conflict-averse." },
  ],
  weaknesses: [
    { title: "Over-Giving and Burnout", description: "Their attention to others can leave no energy for themselves. Burnout arrives quietly and lasts a long time." },
    { title: "Idealistic About People", description: "They can overestimate potential and keep investing in relationships or teams that are not returning the care." },
    { title: "Conflict Avoidance in Personal Matters", description: "They will address big issues for the sake of others, but may swallow their own needs to keep harmony." },
    { title: "Over-Attuned to External Approval", description: "Their sense of self can depend too heavily on how others respond. Disapproval from people they respect can destabilise them." },
    { title: "Hides Their Own Doubts", description: "They often perform confidence they do not fully feel, leaving even close people unable to support them in hard moments." },
  ],
  stressTriggers: [
    "Sustained interpersonal conflict in groups they care about",
    "Feeling unappreciated or invisible despite heavy giving",
    "Working in cultures that are transactional or cruel to vulnerable people",
    "Being criticised on their motives or authenticity",
    "Having their mentorship or leadership ignored or undermined",
    "Losing alone-time for long stretches",
    "Watching someone they care about make a destructive choice",
  ],
  stressSigns: [
    "Uncharacteristic withdrawal and reduced contact with people",
    "Obsessive overthinking and self-doubt on small decisions",
    "Cynicism about people and motives, which is not their default",
    "Physical exhaustion, insomnia, or stress-related illness",
    "Snapping at the very people they usually care for",
    "Intense self-criticism about their competence or worth",
  ],
  recoveryStrategies: [
    "Deliberate alone-time and distance from all demands",
    "One-to-one conversation with someone who takes care of them for once",
    "Physical movement — walking, swimming, yoga, something kind to the body",
    "Journaling to untangle their own feelings from everyone else's",
    "Say a clear, boundary-respecting no to at least one current obligation",
  ],
  socialBattery: 70,
  relationships: {
    narrative: "ENFJs love fully and publicly. They remember details, plan the experience, and work hard to make their partner feel seen and chosen. They show love through attention, emotional attunement, and a steady commitment to the relationship's growth. The risk is pouring so much into the partner that they lose track of their own inner state — and then feeling resentful or hollow without understanding why. They need a partner who consistently pays attention back and who can gently pull them out of over-giving mode.",
    offers: ["Unusual emotional attentiveness and real commitment", "A partner who actively invests in your growth and happiness", "Warmth, celebration, and a relationship that feels like a team"],
    needs: ["Real reciprocity — a partner who sees them, not just receives", "Space to have their own needs and vulnerabilities welcomed", "A partner who is honest about conflict rather than letting it simmer"],
    challenges: ["Tend to over-give and then feel unseen", "Can absorb their partner's moods and lose themselves in the relationship", "May avoid voicing their own needs until the pressure is high"],
    compatibleWith: [
      { type: "INFP", reason: "A deeply imaginative partner whose inner life the ENFJ loves to honour and protect" },
      { type: "INTP", reason: "An intellectual counterweight who challenges the ENFJ's thinking and grounds them" },
      { type: "ISFP", reason: "A quiet, values-driven partner who receives the ENFJ's warmth without demanding performance" },
    ],
  },
  friendships: {
    narrative: "ENFJs are the friends who actually keep the group together. They remember the birthdays, notice who is struggling, and turn loose acquaintances into real community over time. Their friendship is generous, steady, and attentive. The main risk is giving so much that they forget to ask for anything back.",
    positives: ["The friend who checks in on you in the specific week you most needed it", "The friend who makes introductions that change your life", "The friend who holds the group together across years and seasons"],
    watchOuts: ["May over-invest in friends who do not invest back", "Can quietly burn out on the group they are holding together"],
  },
  career: {
    narrative: "ENFJs thrive in work that combines vision, people, and impact. They do their best in teaching, leading, coaching, mentoring, and mission-driven organisations. They can struggle in roles that are cold, extractive, or where their care is treated as weakness rather than strength. Autonomy, a worthy mission, and genuinely good colleagues are all important to their sustained engagement.",
    bestCareers: [
      { label: "Teacher / Professor", icon: "graduation-cap" },
      { label: "HR Director / People Lead", icon: "briefcase" },
      { label: "Non-Profit Leader", icon: "briefcase" },
      { label: "Therapist / Counsellor", icon: "briefcase" },
      { label: "Political Leader", icon: "briefcase" },
      { label: "Executive Coach", icon: "briefcase" },
      { label: "Public Speaker", icon: "briefcase" },
      { label: "Brand / Mission Leader", icon: "briefcase" },
    ],
    leadershipStyle: ["Leads by inspiring a shared purpose and making each person feel crucial", "Invests heavily in one-to-one relationships with direct reports", "Holds clear, values-based standards and will address violations", "Can neglect harsh operational decisions that would wound individuals"],
    asTeammate: ["The person who turns a group of strangers into a team", "Keeps the human layer healthy even under hard deadlines", "Asks how you actually are, and means it"],
    cautionCareers: ["Purely analytical, people-sparse roles (a long way from their strengths)", "Highly transactional, coldly competitive environments"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "Your twenties are the decade of using your gifts openly while learning to protect them. Build the career that lets you lead and mentor, but practice saying no — boundaries are the difference between a sustainable ENFJ and a burned-out one." },
    { phase: "In Your 30s", description: "Your influence is real now; the challenge is depth over breadth. Pour the biggest care into the smallest number of people, and trust that a narrower focus will let you shape them more profoundly. This is also the decade to notice your own needs before everyone else's." },
    { phase: "Midlife", description: "Your inferior Thinking function begins to surface. You may become newly interested in analysis, systems, and first-principles logic. Welcome it; it makes your mentorship sharper and less emotionally dependent." },
    { phase: "Mature Expression", description: "At your best, you become the trusted elder-mentor whose impact compounds through the people you shaped. Your care is still there, but it is now paired with hard-won self-preservation and clarity." },
  ],
  topGrowthChallenges: ["Protect your own energy first — you cannot elevate others from an empty well", "Let people see your uncertainty; they trust you more, not less, when you are real", "Build routines that refill you: solitude, movement, honest conversation"],
  famousPeople: [
    { name: "Oprah Winfrey", role: "Media leader", reason: "Charismatic mentor on a global scale; turned empathy into institutional power" },
    { name: "Saigō Takamori", role: "Samurai & statesman", reason: "Charismatic moral leader who rallied people around shared ideals and loyalty" },
    { name: "Barack Obama", role: "US President", reason: "Inspirational communicator who built coalitions through shared vision" },
    { name: "Maya Angelou", role: "Writer & civil rights leader", reason: "Deep empathy paired with moral clarity and public voice" },
    { name: "Jennifer Lawrence", role: "Actress", reason: "Warm, expressive, emotionally accessible on and off screen" },
    { name: "Nitobe Inazō", role: "Educator & diplomat", reason: "Bridge-builder who interpreted cultures to one another with warmth and conviction" },
    { name: "John Cena", role: "Wrestler & actor", reason: "Warm, values-driven public figure known for mentorship and uplifting others" },
    { name: "Dumbledore", role: "Fictional (Harry Potter)", reason: "Wise mentor who sees potential in young people and holds the space for it" },
    { name: "Malala Yousafzai", role: "Activist", reason: "Young, values-driven advocate for the education of girls worldwide" },
  ],
  typeComparisons: [
    {
      vsType: "INFJ",
      sharedTraits: ["Both use Fe and Ni", "Deeply care about people and purpose", "Natural mentors and visionaries"],
      keyDifferences: ["ENFJs recharge through people and lead from the front; INFJs recharge alone and work mostly behind the scenes", "ENFJs energise whole rooms; INFJs prefer one-to-one depth", "ENFJs rally; INFJs reflect"],
      youMightBeThis: "If large groups drain you even when the cause is right, and you do your best work one-on-one or alone",
    },
    {
      vsType: "ENFP",
      sharedTraits: ["Both extraverted feelers", "Warm, people-focused, inspiring", "Care about meaning and growth"],
      keyDifferences: ["ENFJs want closure and structure; ENFPs stay open and exploratory", "ENFJs are ordered and planful; ENFPs are spontaneous and improvisational", "ENFJs build institutions; ENFPs spark movements"],
      youMightBeThis: "If structure and closure feel stifling and you need constant novelty to stay engaged",
    },
  ],
  affirmations: ["My care is real power when I protect my own well-being first.", "I can be vulnerable and still be a trusted guide — one deepens the other.", "Boundaries are not abandonment; they are how I keep showing up."],
};
