import type { PremiumTypeData } from '../premiumTypeData';

export const ENFP: PremiumTypeData = {
  code: "ENFP",
  name: "The Dreamer",
  tagline: "Rallying people around an exciting new idea with contagious energy",
  accentColor: "hsl(15 80% 58%)",
  traits: ["Extraverted", "Intuitive", "Feeling", "Perceiving"],
  famousQuote: { text: "If you can dream it, you can do it.", person: "Often attributed to dreamers of the ENFP mold" },
  introduction: [
    "ENFPs are the warm, imaginative rallying-points of the type world. They burst with ideas, adore people, and are unusually gifted at making someone feel they have been truly seen. Meaning, curiosity, and connection are the three gods they serve.",
    "ENFPs approach life through a mix of values and possibility. They can turn an ordinary afternoon into something memorable through sheer attention and enthusiasm, and they genuinely care about the people in front of them, not just the crowd.",
    "ENFPs focus on what could be — in themselves, in others, in the world. They are less interested in what already works and more interested in what might work, if only someone believed in it. They tend to be imaginative, expressive, empathic, and allergic to cages.",
    "ENFPs are usually excellent at igniting things — teams, conversations, friendships, projects. They can draw out the quiet person in the group and hand them a microphone. The harder part is often sustaining: the steady maintenance of what they start can feel like a cage.",
    "Because ENFPs live so much on the surface of connection and ideas, others sometimes underestimate the depth underneath. Under the sparkle is a Fi-driven inner compass that is non-negotiable. They will walk away from anything — career, relationship, friendship — that violates what matters to them.",
    "Others see ENFPs as warm, funny, slightly chaotic, and surprisingly intense once you get past the social skin. Inside their circle they are devoted and loyal. They need freedom, novelty, and real depth, and they quietly wilt in environments that flatten them.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Extraverted Intuition", abbr: "Ne", description: "Your primary mode. You perceive possibilities, connections, and potentials everywhere. Ideas multiply in your head and across conversations; this is the engine of your creativity and your social spark." },
    auxiliary: { name: "Introverted Feeling", abbr: "Fi", description: "Your support system. Behind the energy is a deep, private set of values. They are what stop your ideas from being merely clever — they anchor everything in what is meaningful to you." },
    tertiary: { name: "Extraverted Thinking", abbr: "Te", description: "Developing with age. Over time you build more structure, follow-through, and practical execution. It turns good ideas into shipped outcomes." },
    inferior: { name: "Introverted Sensing", abbr: "Si", description: "Your hidden edge and stress trigger. Routine, tradition, and the body can feel foreign. Under heavy stress you may fixate on past mistakes, worry about your health, or lurch into uncharacteristic rigidity." },
  },
  strengths: [
    { title: "Idea Generation", description: "ENFPs produce an abundance of possibilities. They are the catalyst in any brainstorm and the reason a dead conversation suddenly comes alive." },
    { title: "Genuine Warmth", description: "Their interest in people is real. Even strangers feel seen by an ENFP within minutes." },
    { title: "Persuasive Enthusiasm", description: "They can sell a vision by making it feel meaningful and urgent. Their excitement is contagious in a way that pulls others into motion." },
    { title: "Values Under the Sparkle", description: "Beneath the energy is a serious inner compass. They refuse to do work that violates what they believe." },
    { title: "Bridging Different Worlds", description: "They move easily between disciplines, cultures, and social groups — and translate between them with unusual skill." },
    { title: "Courage to Change Direction", description: "When something stops aligning with their values, they leave. Their willingness to restart is a real strength." },
  ],
  weaknesses: [
    { title: "Struggles with Follow-Through", description: "New ideas excite them more than old ones finish. Projects can pile up in the interesting middle." },
    { title: "Scatter and Distraction", description: "They can chase too many threads at once, leaving everything shallow. Focus is their lifelong practice." },
    { title: "Over-Absorbs Other People's Emotions", description: "Their empathy can blur into entanglement. They take on what is not theirs to carry." },
    { title: "Resists Routine and Structure", description: "They may skip the boring systems that would actually amplify their gifts." },
    { title: "Self-Critical in Private", description: "Under the warmth they can be harsh on themselves, especially about follow-through and productivity." },
  ],
  stressTriggers: [
    "Rigid, routine, soul-deadening environments",
    "Being pressured to suppress their values for a paycheck",
    "Constant administrative demands with no creative surface",
    "Being micromanaged or told to stop pursuing new ideas",
    "Environments that feel cold, transactional, or politically cruel",
    "Loss of a meaningful relationship or community",
    "Feeling creatively blocked for long stretches",
  ],
  stressSigns: [
    "Uncharacteristic withdrawal and loss of their usual spark",
    "Fixating on past mistakes and physical symptoms",
    "Rigid, negative thinking that is unlike their normal expansive mind",
    "Procrastination that becomes paralysis",
    "Snapping at loved ones over small triggers",
    "Emotional eating, spending, or escape into distraction",
  ],
  recoveryStrategies: [
    "A change of scenery — a new city, a walk, anywhere that breaks routine",
    "One honest, unhurried conversation with a safe, non-judgemental friend",
    "Creative play with no outcome attached — art, music, writing for themselves",
    "Physical movement — dance, sport, long walks",
    "Deliberately close three open tabs before starting any new project",
  ],
  socialBattery: 85,
  relationships: {
    narrative: "ENFPs fall in love with a person, not a checklist. They pursue relationships with warmth, curiosity, and a longing for real soul-to-soul depth. They show love through attention, playfulness, spontaneous gestures, and long emotionally-honest conversations. The risk is their tendency to idealise in the beginning and lose interest when the relationship hits routine. They need a partner who is emotionally real, values novelty and depth equally, and stays engaged as the relationship evolves.",
    offers: ["Deep emotional presence and genuine curiosity about who you are", "A fun, inventive partner who never lets the relationship go stale by default", "Values-driven loyalty under the sparkle"],
    needs: ["A partner who can meet their depth and their energy", "Freedom to be themselves — no crushing routines or small cages", "Real emotional honesty and willingness to have the hard conversation"],
    challenges: ["May idealise a new partner and crash when reality arrives", "Can get bored in the healthy-but-quiet phase of a long relationship", "Tend to absorb a partner's emotions and lose their own footing"],
    compatibleWith: [
      { type: "INTJ", reason: "A deep strategist who stabilises the ENFP's energy and provides structure" },
      { type: "INFJ", reason: "A rare partner who understands both the depth and the idealism underneath the spark" },
      { type: "INTP", reason: "An intellectually curious counterpart who meets them in the idea-world" },
    ],
  },
  friendships: {
    narrative: "ENFPs collect friends easily and invest in the ones who meet them at depth. They can disappear and reappear with full presence, remember very specific details about you, and turn an ordinary dinner into the best night of the month. Their friendship is generous and slightly unpredictable.",
    positives: ["The friend who reminds you of who you are when you have forgotten", "The friend who turns a casual plan into a memory you will talk about for years", "The friend who actually asks the follow-up question and listens to the answer"],
    watchOuts: ["May over-commit socially and then disappear", "Can absorb a friend's crisis so deeply it derails their own week"],
  },
  career: {
    narrative: "ENFPs thrive in people-facing, creative, meaning-rich work. They shine in roles that let them imagine, connect, persuade, and re-invent. They tend to struggle in work that is repetitive, cold, or stripped of values. The ideal ENFP career has autonomy, a worthwhile mission, capable colleagues, and real creative surface.",
    bestCareers: [
      { label: "Writer / Journalist", icon: "briefcase" },
      { label: "Marketer / Brand Strategist", icon: "briefcase" },
      { label: "Product Manager", icon: "briefcase" },
      { label: "Teacher / Facilitator", icon: "graduation-cap" },
      { label: "Psychologist / Counsellor", icon: "briefcase" },
      { label: "Creative Director", icon: "briefcase" },
      { label: "Non-Profit Lead", icon: "briefcase" },
      { label: "Actor / Performer", icon: "briefcase" },
    ],
    leadershipStyle: ["Leads by vision and warmth; makes each person feel essential", "Prefers collaborative, high-trust teams over hierarchy", "Generates ideas constantly and needs a strong operator beside them", "Can struggle with hard, people-hurting decisions"],
    asTeammate: ["The person who makes every meeting a little more human", "Unlocks stalled projects with a fresh angle nobody else saw", "Notices who is not being heard and makes room for them"],
    cautionCareers: ["Long operational roles with no creative or human surface", "Rigid, values-empty corporate environments"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "Your twenties are the decade of wide exploration. Follow the interesting problems, fall in love with several causes, and build the muscle of finishing at least one of them. Depth will matter more than you think in your thirties." },
    { phase: "In Your 30s", description: "Now the task is translating energy into durable work. Pick the craft, mission, or company and commit to it past the boring middle. Pair a steady operator with your creative sparks and watch what becomes possible." },
    { phase: "Midlife", description: "Your inferior Sensing function begins to break through. You may develop unexpected interests in health, ritual, tradition, or a long-term place. Welcome it; it grounds the energy that has carried you so far." },
    { phase: "Mature Expression", description: "At your best, you become the rare elder who is still creative, warm, and values-led — but also deeply reliable. Your later-life work lands harder because you finally stuck with one thing long enough for mastery." },
  ],
  topGrowthChallenges: ["Finish what you start — one completed project teaches you more than ten abandoned ones", "Protect your own inner life; you are not required to carry every friend's crisis", "Build routines that refill you — your creativity runs on rest, not just stimulation"],
  famousPeople: [
    { name: "Robin Williams", role: "Actor & comedian", reason: "Inventive, warm, bottomlessly expressive, deeply empathic" },
    { name: "Walt Disney", role: "Entertainment entrepreneur", reason: "Imagination at industrial scale; believed in the vision first" },
    { name: "Ellen DeGeneres", role: "TV host & comedian", reason: "Warm, funny, emotionally connective with a wide public" },
    { name: "Che Guevara", role: "Revolutionary", reason: "Values-driven, restless, unwilling to accept the world as given" },
    { name: "Robert Downey Jr.", role: "Actor", reason: "Inventive, charming, vulnerable, full of reinvention" },
    { name: "Ariel", role: "Fictional (The Little Mermaid)", reason: "Curious, warm, driven by longing for a world she hasn't seen" },
    { name: "Jennifer Aniston", role: "Actress", reason: "Warm, playful, widely beloved for her emotional accessibility" },
  ],
  typeComparisons: [
    {
      vsType: "INFP",
      sharedTraits: ["Both Fi-and-Ne types", "Values-driven, imaginative, authentic", "Deeply caring once trust is earned"],
      keyDifferences: ["ENFPs recharge through people and process out loud; INFPs recharge in solitude and process inward", "ENFPs are expansively warm; INFPs are quietly selective", "ENFPs speak; INFPs write"],
      youMightBeThis: "If you come alive alone and the noise of many relationships drains you even when you love the people",
    },
    {
      vsType: "ENTP",
      sharedTraits: ["Both Ne-dominant", "Idea-rich, persuasive, allergic to boredom", "Restless, exploratory"],
      keyDifferences: ["ENFPs lead with values (Fi); ENTPs lead with logic (Ti)", "ENFPs connect for meaning; ENTPs provoke for clarity", "ENFPs build vibe; ENTPs build the argument"],
      youMightBeThis: "If your ideas are driven by logical consistency and you enjoy debate more than emotional resonance",
    },
  ],
  affirmations: ["My curiosity changes rooms — I finish what I start and let it change the world.", "I can stay deeply myself while loving many people well.", "Depth and sparkle belong together; one does not cancel the other."],
};
