import type { PremiumTypeData } from '../premiumTypeData';

export const ENTJ: PremiumTypeData = {
  code: "ENTJ",
  name: "The Leader",
  tagline: "Leading a team through a complex challenge to deliver outstanding results",
  accentColor: "hsl(280 60% 50%)",
  traits: ["Extraverted", "Intuitive", "Thinking", "Judging"],
  famousQuote: { text: "The best way to predict the future is to create it.", person: "Often attributed to leaders of the ENTJ mold" },
  introduction: [
    "ENTJs are born commanders. They see a complex problem, mentally map out the solution, and start mobilising people and resources toward it almost immediately. They move fast, think long-range, and are comfortable holding a strong opinion in a room full of people who disagree.",
    "ENTJs approach problems logically and strategically. They are natural decision-makers and rarely hesitate once the analysis is in. They can be blunt, demanding, and forceful — not out of cruelty, but because they genuinely believe momentum beats perfection.",
    "ENTJs focus on the future and on the system. They are less interested in what is true today and more interested in what could be true in five years. They tend to be visionary, logical, disciplined, and uncompromising on excellence.",
    "ENTJs are usually excellent executives because they combine long-range vision with operational drive. They see the goal, map the path, assign the people, set the milestones, and push the whole machine forward until the result lands.",
    "Because ENTJs are confident and direct, they sometimes overwhelm more reserved teammates. They move faster than most people are comfortable with and may cut corners on relational maintenance in pursuit of results. They need feedback mechanisms to know when to slow down.",
    "Others see ENTJs as powerful, articulate, self-assured, and occasionally intimidating. Inside a small circle they can be warm, funny, and fiercely loyal — but they take commitments seriously and expect the same in return.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Extraverted Thinking", abbr: "Te", description: "Your primary mode. You impose structure, logic, and measurable progress on the outer world. You organise people and resources with unusual speed, and your instinct is always to move from analysis to action." },
    auxiliary: { name: "Introverted Intuition", abbr: "Ni", description: "Your support system. You see long-range patterns, futures, and strategic implications that inform the plans you are driving. This is the source of your ability to act decisively toward a distant goal." },
    tertiary: { name: "Extraverted Sensing", abbr: "Se", description: "Developing with age. You increasingly enjoy the immediate, physical present — travel, food, sport, adventure. It balances your future-orientation with richer experience of now." },
    inferior: { name: "Introverted Feeling", abbr: "Fi", description: "Your hidden edge and stress trigger. Your personal values run deep but rarely surface. Under stress you may erupt emotionally, feel unexpectedly wounded, or become uncharacteristically moralistic." },
  },
  strengths: [
    { title: "Decisive Leadership", description: "ENTJs make the call when everyone else is still deliberating. They take responsibility for the decision and own the consequences, good or bad." },
    { title: "Long-Range Vision", description: "They see where the organisation, the industry, or the project needs to be in five years and work backward from there with disciplined steps." },
    { title: "Strategic Thinking", description: "They frame every move against the larger plan. Tactics that make sense in isolation get rejected if they do not serve the long arc." },
    { title: "Strong Willpower", description: "ENTJs push through obstacles that would break most people. They rarely quit a project they have committed to, and they expect the same resilience from their teams." },
    { title: "Charismatic Communicator", description: "They can articulate a vision in a way that pulls capable people toward it. They make the complex sound urgent and achievable." },
    { title: "Efficient Executor", description: "They hate wasted motion. They cut meetings, simplify processes, and remove friction so that the team can actually ship." },
  ],
  weaknesses: [
    { title: "Impatient and Demanding", description: "ENTJs move at a speed that can exhaust collaborators. Their urgency can feel like pressure and their standards can feel like constant judgement." },
    { title: "Can Be Overbearing", description: "They tend to dominate rooms and discussions without meaning to. Quieter voices and good ideas can get steamrolled in the process." },
    { title: "Dismissive of Emotions", description: "They can treat feelings — their own and others' — as inefficient data. This lands badly with partners, teammates, and direct reports who need more care." },
    { title: "Stubborn Once Decided", description: "Their confidence in their own analysis can tip into rigidity. Changing course, once committed, is unusually hard for them." },
    { title: "Struggles to Delegate Fully", description: "Despite believing in delegation, ENTJs often hover, correct, and take back the work when it is not done exactly their way." },
  ],
  stressTriggers: [
    "Being stuck in bureaucratic, slow-moving environments",
    "Working with people who will not commit to a decision",
    "Having their competence or authority publicly challenged by someone unprepared",
    "Endless small, emotional conflicts that block the actual work",
    "Losing control of the timeline, the plan, or the team",
    "Being asked to sit passively when they can see what needs to happen",
    "Relationships where their drive is interpreted as aggression",
  ],
  stressSigns: [
    "Becoming explosively short-tempered with people around them",
    "Uncharacteristic emotional outbursts — anger, tears, moral outrage",
    "Micromanaging every detail instead of delegating",
    "Becoming hyper-critical of themselves over small mistakes",
    "Withdrawing from the team and going quiet unexpectedly",
    "Cynical, cutting humour directed at peers or subordinates",
  ],
  recoveryStrategies: [
    "Hard physical exercise — lifting, running, sport — to burn off the charge",
    "A full, deliberate break from work with no goals and no metrics",
    "Talk it out with one trusted peer who is willing to push back",
    "Re-anchor on the long-term plan to de-dramatise the current setback",
    "Spend time with people who love you outside of your professional identity",
  ],
  socialBattery: 85,
  relationships: {
    narrative: "ENTJs bring the same drive to relationships as to everything else — high standards, long-term intent, and a willingness to work at it. They are loyal, ambitious partners who want a real teammate, not an accessory. They express love through building a life together: solving problems, opening doors, and backing their partner's biggest goals. They can struggle with pure emotional presence, and need a partner who can call them out when the project manager energy spills into the relationship.",
    offers: ["A powerful, ambitious partner who is genuinely invested in your success", "Clarity, decisiveness, and real follow-through on commitments", "A strategic ally who will help you think bigger about your own life"],
    needs: ["Intellectual respect and a partner who can hold their own in debate", "Directness — hints and subtle signals do not reach them", "Shared ambition or at least real respect for yours"],
    challenges: ["Can treat the relationship like a project to optimise rather than inhabit", "Bluntness and urgency can feel like pressure to a softer partner", "Struggles to be present emotionally when work is demanding"],
    compatibleWith: [
      { type: "INFP", reason: "A soft, imaginative counterweight that humanises the ENTJ's drive" },
      { type: "INTP", reason: "A brilliant analytical peer who questions the plan and sharpens the thinking" },
      { type: "INTJ", reason: "A shared long-range mind — two strategists who respect each other's autonomy" },
    ],
  },
  friendships: {
    narrative: "ENTJs are loyal, high-agency friends who treat their inner circle as a life investment. They will push you, challenge you, and take your ambitions more seriously than you take them yourself. They tend to prefer a small number of real friends to a wide social network, and are happy to spend months planning a big shared adventure.",
    positives: ["The friend who will actually make the introduction, push the project, or fund the idea", "The friend who calls out your self-deception when nobody else will", "The friend who shows up at the critical moment with a plan and a backup plan"],
    watchOuts: ["Can turn casual conversation into a performance review", "May drop friends who they decide are not growing or serious enough"],
  },
  career: {
    narrative: "ENTJs are built for leadership of complex operations. They thrive in roles where they can set direction, build and drive a team, and measure real results. They tend to be restless in flat, ambiguous environments without a clear ladder, and can clash with cultures that prize consensus over speed.",
    bestCareers: [
      { label: "CEO / Executive", icon: "briefcase" },
      { label: "Management Consultant", icon: "briefcase" },
      { label: "Corporate Lawyer", icon: "scale" },
      { label: "Investment Banker", icon: "bar-chart" },
      { label: "Entrepreneur", icon: "briefcase" },
      { label: "Political Leader", icon: "briefcase" },
      { label: "Military Commander", icon: "shield" },
      { label: "Strategy Director", icon: "briefcase" },
    ],
    leadershipStyle: ["Leads from the front — publicly sets the vision and the bar", "Demands clarity of ownership and accountability from everyone", "Moves fast; kills projects quickly when they are not working", "Leans into confrontation rather than avoiding it"],
    asTeammate: ["The person who turns a vague plan into a scoped, scheduled, owned piece of work", "Pushes the team to think bigger and move faster than they would alone", "Says what everyone else is thinking but is too polite to say"],
    cautionCareers: ["Pure support or service roles with no room to lead", "Highly bureaucratic, tenure-based organisations that reward waiting"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "Your twenties are the decade of earning your authority. Take on more than you think you can handle and prove you can deliver. But temper the ambition with humility — you will earn more trust as a junior who listens well than as one who bulldozes early." },
    { phase: "In Your 30s", description: "Your competence is real now; the frontier is empathy. Learn to slow down for the people you lead, invest in one-on-ones, and distinguish the person from the output. The leaders who rise further in their thirties are the ones who can keep talent, not just hire it." },
    { phase: "Midlife", description: "The inferior Feeling function begins to break through. You may become unexpectedly moved by family, legacy, mentorship, and your own inner life. Treat these shifts as maturity, not weakness, and let them shape the leader you are becoming." },
    { phase: "Mature Expression", description: "At your best, you become the rare executive who is decisive and humane — respected for both what you ship and how you treat people along the way. Power sits easily on you because you no longer need to prove you have it." },
  ],
  topGrowthChallenges: ["Before you correct, ask if the person needs a coach, a colleague, or just a human in the moment", "Delegate fully — your job is to build leaders, not to be the only competent person in the room", "Make space for your own emotions; the feelings you ignore eventually run the decisions"],
  famousPeople: [
    { name: "Steve Jobs", role: "Co-founder of Apple", reason: "Visionary, demanding, ruthless about quality; set long-term direction and shipped it" },
    { name: "Itō Hirobumi", role: "First Prime Minister of Japan", reason: "Strategic architect of a national constitution and modern political system" },
    { name: "Margaret Thatcher", role: "Former UK Prime Minister", reason: "Decisive, strategic, unyielding once committed to a course" },
    { name: "Gordon Ramsay", role: "Chef & television host", reason: "Direct, results-oriented, no patience for mediocrity" },
    { name: "Franklin D. Roosevelt", role: "US President", reason: "Bold, strategic, led a nation through crisis with long-range plans" },
    { name: "Minamoto no Yoritomo", role: "Founder of the Kamakura shogunate", reason: "Decisive organiser who established a durable command structure that ruled for centuries" },
    { name: "Kamala Harris", role: "Politician", reason: "Prosecutorial sharpness, public leadership, clear ambition" },
    { name: "Miranda Priestly", role: "Fictional (The Devil Wears Prada)", reason: "Commanding, high-standards, uncompromising executive energy" },
    { name: "Napoleon Bonaparte", role: "General & emperor", reason: "Decisive commander, strategic thinker, relentless executor" },
  ],
  typeComparisons: [
    {
      vsType: "ESTJ",
      sharedTraits: ["Both decisive, Te-dominant leaders", "High standards, high follow-through", "Natural managers"],
      keyDifferences: ["ENTJs think strategically and long-range; ESTJs focus on present operations and proven systems", "ENTJs redesign systems; ESTJs run them beautifully", "ENTJs tolerate risk and disruption; ESTJs prefer stability and order"],
      youMightBeThis: "If you thrive inside an established structure rather than rebuilding it from scratch",
    },
    {
      vsType: "INTJ",
      sharedTraits: ["Both strategic, long-range, Thinking-dominant", "Plan years ahead", "High standards for themselves"],
      keyDifferences: ["ENTJs lead publicly and mobilise people; INTJs operate privately and delegate", "ENTJs recharge through action and leadership; INTJs recharge through solitude", "ENTJs want the team; INTJs want the quiet study"],
      youMightBeThis: "If the thought of leading daily meetings exhausts you and your instinct is to plan in silence and hand off the finished blueprint",
    },
  ],
  affirmations: ["My decisiveness and drive are real gifts — used with care, they lift every team I touch.", "I can lead with strength and still slow down for the people I lead.", "The feelings I pay attention to make me a sharper leader, not a softer one."],
};
