import type { PremiumTypeData } from '../premiumTypeData';

export const ENTP: PremiumTypeData = {
  code: "ENTP",
  name: "The Innovator",
  tagline: "Generating breakthrough ideas in rapid-fire brainstorming sessions",
  accentColor: "hsl(295 60% 55%)",
  traits: ["Extraverted", "Intuitive", "Thinking", "Perceiving"],
  famousQuote: { text: "The reasonable man adapts himself to the world; the unreasonable one persists in trying to adapt the world to himself.", person: "Often attributed to thinkers of the ENTP mold" },
  introduction: [
    "ENTPs are the idea-engines of the type world — fast, verbal, provocative, and electric in a room. They chase connections between unrelated fields, enjoy challenging consensus, and treat the status quo as a draft that was never meant to be final.",
    "ENTPs approach problems playfully and analytically. They enjoy debate for its own sake, will argue both sides just to see the structure, and tend to find the hidden flaw in any plan within minutes. They can be witty, confrontational, restless, and intellectually fearless.",
    "ENTPs focus on possibility. The phrase 'what if' is practically their native tongue. They are less interested in preserving what already works and more interested in inventing what could work better. They tend to be inventive, articulate, spontaneous, and allergic to boredom.",
    "ENTPs are usually excellent at starting things — companies, projects, conversations, movements. The hard part for them is often finishing: the early ambiguity where ideas feel possible is their paradise; the late-stage polish can feel like punishment.",
    "Because ENTPs challenge almost everything, others sometimes mistake their provocations for personal attack. They rarely mean them that way. They are testing the idea, not the person, and will instantly respect someone who pushes back with rigour.",
    "Others see ENTPs as charming, clever, contrarian, and occasionally exhausting. Inside their small circle they are warm, loyal, and fiercely protective. They take friendship and creative partnership seriously even when almost nothing else looks serious.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Extraverted Intuition", abbr: "Ne", description: "Your primary mode. You perceive patterns, possibilities, and hidden connections everywhere. Ideas multiply faster than you can use them, and this is the engine of your creative, improvisational edge." },
    auxiliary: { name: "Introverted Thinking", abbr: "Ti", description: "Your support system. You filter the flood of ideas through internal logical rigour, keeping only the ones that hold up under pressure. This is why your provocations usually land on something real." },
    tertiary: { name: "Extraverted Feeling", abbr: "Fe", description: "Developing with age. Over time you grow more attuned to group dynamics, mood, and how your ideas actually land on people. It softens the debate reflex into influence." },
    inferior: { name: "Introverted Sensing", abbr: "Si", description: "Your hidden edge and stress trigger. Routine, tradition, and bodily maintenance feel foreign to you. Under heavy stress you may lurch into uncharacteristic nostalgia, fixation on the past, or physical symptoms you usually ignore." },
  },
  strengths: [
    { title: "Rapid Ideation", description: "ENTPs generate ten plausible ideas where others generate one. In any brainstorm they are usually the accelerant the whole group benefits from." },
    { title: "Intellectual Versatility", description: "They can move fluidly across domains, finding useful analogies between business, art, science, and politics. Their thinking is rarely siloed." },
    { title: "Persuasive and Articulate", description: "They translate complex ideas into vivid, memorable language. They can sell a vision to a skeptical audience without flattening it." },
    { title: "Debate and Challenge", description: "They are not afraid to push back on bad reasoning, even when it is socially costly. Groups that include a good ENTP make better decisions as a result." },
    { title: "Resilience Under Pressure", description: "ENTPs thrive in ambiguity. When a plan blows up, they are usually the calmest person in the room — because they are already designing three new ones." },
    { title: "Catalytic Energy", description: "They pull other people into motion. Projects that were stalled for months start moving again when an ENTP gets involved." },
  ],
  weaknesses: [
    { title: "Struggles with Follow-Through", description: "Finishing bores them. Projects can pile up in the 70% done stage because the interesting part is over." },
    { title: "Argumentative for Its Own Sake", description: "Their love of debate can exhaust the people around them. Not every conversation needs to be a case to win." },
    { title: "Easily Bored and Distracted", description: "Without novelty, they lose engagement fast. This can cost them deep expertise and stable commitments." },
    { title: "Insensitive to Emotional Tone", description: "When they are in idea-mode, they can trample on the feelings of teammates who needed warmth, not critique." },
    { title: "Overconfident in New Plans", description: "They tend to underestimate execution cost and routine maintenance. The next idea always looks easier than the last one actually was." },
  ],
  stressTriggers: [
    "Repetitive, routine work with no novelty or debate",
    "Rigid hierarchies that punish challenge and reward compliance",
    "Working with people who take everything personally",
    "Deadlines that force them to ship before the idea feels complete",
    "Being told to stop questioning and just follow the process",
    "Environments where bureaucracy kills speed and experimentation",
    "Social settings that demand constant emotional sensitivity and no edge",
  ],
  stressSigns: [
    "Uncharacteristic withdrawal and sudden silence",
    "Obsessing over past events, old grievances, or physical symptoms",
    "Rigid, stuck thinking that looks nothing like their usual fluidity",
    "Snapping sarcastically at people they normally tolerate",
    "Neglecting sleep, meals, and basic routines",
    "Paradoxical over-commitment — saying yes to everything to feel alive again",
  ],
  recoveryStrategies: [
    "Change context — travel, new city, new venue, new people",
    "Spend a few hours with a wildly unrelated book, podcast, or conversation",
    "Move the body hard — sport, long walks, anything physical and novel",
    "Let one trusted friend hear the unfiltered monologue without fixing it",
    "Deliberately close three open projects before starting a new one",
  ],
  socialBattery: 80,
  relationships: {
    narrative: "ENTPs approach love as the best possible conversation — curious, playful, a little combative, endlessly interesting. They are loyal in principle and willing to work on the relationship, but they need a partner who is genuinely engaging and comfortable with their restless energy. They show love through ideas, shared adventures, and constant gentle provocation. The biggest pitfall is treating the relationship the way they treat their projects — fascinated at the start, less patient once routine sets in.",
    offers: ["A relationship that is never boring — ideas, adventures, and real partnership", "Fierce loyalty to the people who earn their deep trust", "A partner who will challenge you and help you grow bigger"],
    needs: ["A partner who can hold their own intellectually and emotionally", "Space to pursue their many interests without guilt", "Honest directness; hints and passive signals do not land"],
    challenges: ["Can debate when they should simply be present", "Tend to underestimate the work of long-term relational maintenance", "May get bored in a healthy but quieter phase of the relationship"],
    compatibleWith: [
      { type: "INFJ", reason: "A thoughtful partner who anchors the ENTP's energy in real depth and meaning" },
      { type: "INTJ", reason: "Strategic counterpart who turns the ENTP's sparks into a long-range plan" },
      { type: "ENFP", reason: "A fellow Ne-type who shares the delight in ideas and adventure" },
    ],
  },
  friendships: {
    narrative: "ENTPs collect interesting people the way other types collect books. They can drift in and out of social groups, show up intermittently, and still be beloved — because when they are there, they are fully there. They are the friend who will call you at 11pm with a wild new plan and actually make it happen.",
    positives: ["The friend who turns an ordinary dinner into a real conversation", "The friend who will champion your weirdest idea out loud", "The friend who is always up for the adventure you half-joked about"],
    watchOuts: ["Can debate a friend into a corner and miss that they are upset", "May forget to maintain the friendship and then reappear at full volume"],
  },
  career: {
    narrative: "ENTPs thrive in roles that reward novel thinking, persuasion, and comfort with ambiguity. They excel in early-stage work — launches, pitches, invention, re-design — and tend to struggle in long, steady, operational roles. The ideal ENTP career has multiple problems, real autonomy, and a team capable enough that they never become the bottleneck on execution.",
    bestCareers: [
      { label: "Entrepreneur / Founder", icon: "briefcase" },
      { label: "Product Manager", icon: "briefcase" },
      { label: "Venture Capitalist", icon: "briefcase" },
      { label: "Management Consultant", icon: "briefcase" },
      { label: "Journalist", icon: "briefcase" },
      { label: "Marketer / Strategist", icon: "briefcase" },
      { label: "Trial Lawyer", icon: "scale" },
      { label: "Creative Director", icon: "briefcase" },
    ],
    leadershipStyle: ["Leads through vision, persuasion, and infectious curiosity", "Encourages dissent and wants real debate before committing", "Changes direction quickly when evidence shifts — sometimes too quickly", "Prefers flat, high-trust teams over hierarchical bureaucracy"],
    asTeammate: ["The person who questions the assumption everyone else accepted", "Unlocks stalled conversations with a new angle", "Happiest in launch and early iteration, less so in maintenance"],
    cautionCareers: ["Long-cycle operational roles with no creative surface area", "Highly regulated, process-heavy environments that punish improvisation"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "Your twenties are an exuberant, wide-ranging decade. Follow the interesting problems, collect skills, and build your catalogue of ideas. But pick at least one thing and drive it past the boring middle — your peers who do this end up with real leverage in their thirties." },
    { phase: "In Your 30s", description: "Your challenge now is depth and completion. One finished business, book, or craft beats ten half-built ones. This is also the decade to stop mistaking debate for intimacy — practice real emotional presence with the people closest to you." },
    { phase: "Midlife", description: "Your inferior Sensing function starts to surface. You may become unexpectedly interested in health, tradition, family, and the stable rhythms of life. Welcome these shifts; they ground the wild energy you have always ridden." },
    { phase: "Mature Expression", description: "At your best, you become the rare elder who is still inventive — provocative, playful, but deeply reliable. Your ideas finally land because your follow-through has caught up to your imagination." },
  ],
  topGrowthChallenges: ["Finish the thing before you start the next thing — half-done projects teach less than one completed one", "Notice when your debate is costing you connection, and soften on purpose", "Schedule boring maintenance — health, finances, relationships — with the same energy you give to new ideas"],
  famousPeople: [
    { name: "Thomas Edison", role: "Inventor", reason: "Endless ideas, rapid prototyping, relentless reinvention" },
    { name: "Fukuzawa Yukichi", role: "Educator & writer", reason: "Idea-rich reformer who debated tradition and championed new ways of thinking" },
    { name: "Leonardo da Vinci", role: "Polymath", reason: "Crossed fields constantly; pursued every interesting problem" },
    { name: "Mark Twain", role: "Writer", reason: "Witty, provocative, skeptical of every cherished idea of his time" },
    { name: "Richard Feynman", role: "Physicist", reason: "Playful, questioning, refused to accept anything he had not re-derived" },
    { name: "Katsu Kaishū", role: "Statesman & naval officer", reason: "Witty, persuasive negotiator who reframed conflicts and brokered unlikely deals" },
    { name: "Sacha Baron Cohen", role: "Actor & comedian", reason: "Pushes social boundaries to reveal truth; performs with analytical depth" },
    { name: "Tyrion Lannister", role: "Fictional (Game of Thrones)", reason: "Witty, articulate, strategic, and profoundly contrarian" },
    { name: "Benjamin Franklin", role: "Inventor & statesman", reason: "Polymath who invented, wrote, and argued his way into history" },
  ],
  typeComparisons: [
    {
      vsType: "INTP",
      sharedTraits: ["Both Ne-plus-Ti minds who love ideas", "Skeptical of unjustified rules", "Enjoy debate and abstract play"],
      keyDifferences: ["ENTPs externalise ideas and test them in conversation; INTPs refine them internally first", "ENTPs want an audience; INTPs want solitude", "ENTPs launch; INTPs publish once it is water-tight"],
      youMightBeThis: "If you would rather perfect the theory in private before anyone else hears it, and dislike performing your ideas in real time",
    },
    {
      vsType: "ENFP",
      sharedTraits: ["Both extraverted intuitives", "Idea-rich and persuasive", "Restless, exploratory, and allergic to boredom"],
      keyDifferences: ["ENTPs lead with logic and love debate; ENFPs lead with values and care about impact", "ENTPs provoke for clarity; ENFPs connect for meaning", "ENTPs build the argument; ENFPs build the vibe"],
      youMightBeThis: "If your ideas are driven by what moves people emotionally rather than by what holds up logically",
    },
  ],
  affirmations: ["My ideas reach the world only when I finish what I start.", "I can be sharp and still be kind; the truth lands better when it is delivered with care.", "Depth is not the enemy of curiosity — it is what lets curiosity count."],
};
