import type { PremiumTypeData } from '../premiumTypeData';

export const ESFJ: PremiumTypeData = {
  code: "ESFJ",
  name: "The Caretaker",
  tagline: "Bringing people together and making everyone feel at home",
  accentColor: "hsl(345 65% 55%)",
  traits: ["Extraverted", "Observant", "Feeling", "Judging"],
  famousQuote: { text: "The best way to find yourself is to lose yourself in the service of others.", person: "Often attributed to caretakers of the ESFJ mold" },
  introduction: [
    "ESFJs are the warm, organising heart of every community they enter. They remember everyone's name, throw the gathering that becomes tradition, and instinctively check on the person sitting quietly in the corner. They turn acquaintances into families.",
    "ESFJs approach life with attentive warmth and real practical competence. They track what people need, remember what matters, and organise the logistics that keep a household, team, or community running. Care and order go hand in hand for them.",
    "ESFJs focus on the present and on the people in front of them. They trust tradition, shared values, and the lived experience of their community. They tend to be warm, conscientious, loyal, and quietly driven to hold the group together.",
    "ESFJs are usually excellent teachers, nurses, managers, hosts, and community organisers. They bring a rare combination of social attunement and operational reliability, and they are happiest when they can meet specific, visible human needs.",
    "Because ESFJs care so much and so visibly, they can take on too much and feel hurt when others do not reciprocate. Their self-worth can become too entangled with being needed. Learning to receive care — and to keep caring when unthanked — is their ongoing growth.",
    "Others see ESFJs as warm, dependable, organised, and sometimes a little too attentive to social rules. Inside their circle they are playful, loving, and deeply loyal. They take their roles — friend, partner, parent, host — seriously and invest heavily in the people they have chosen.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Extraverted Feeling", abbr: "Fe", description: "Your primary mode. You tune into the emotional field of any room almost automatically. Your gift is reading social needs and quietly meeting them before anyone has to ask." },
    auxiliary: { name: "Introverted Sensing", abbr: "Si", description: "Your support system. You hold a rich inner library of how things have been — traditions, routines, people, places. It is what makes your care so specific and well-remembered." },
    tertiary: { name: "Extraverted Intuition", abbr: "Ne", description: "Developing with age. Over time you grow more open to new ideas, possibilities, and departures from tradition. It keeps your loyalty flexible rather than brittle." },
    inferior: { name: "Introverted Thinking", abbr: "Ti", description: "Your hidden edge and stress trigger. Cold, detached logic is not home. Under heavy stress you may over-analyse, obsess over logical details, or suddenly distrust your usually strong people-reading." },
  },
  strengths: [
    { title: "Warm, Practical Care", description: "ESFJs translate love into action — meals, plans, help in the exact form that was needed. Their care is never abstract." },
    { title: "Building Community", description: "They create cohesive groups and keep them running. Families, teams, and neighbourhoods quietly depend on an ESFJ." },
    { title: "Attention to People as Individuals", description: "They remember what matters to each person and treat them accordingly. No one is a faceless unit in an ESFJ's world." },
    { title: "Dependable Follow-Through", description: "They keep their commitments. If an ESFJ said they would be there, they will be." },
    { title: "Reading Emotional Undercurrents", description: "They notice tension, hurt, and unspoken need before anyone says anything aloud." },
    { title: "Loyalty in Hard Seasons", description: "When life gets hard, ESFJs are the ones who keep showing up week after week after week." },
  ],
  weaknesses: [
    { title: "Over-Attuned to Approval", description: "Their sense of self can depend too heavily on others' reactions. Disapproval from someone they respect stings disproportionately." },
    { title: "Struggles to Say No", description: "They give until they are empty, and can quietly resent the people who kept taking." },
    { title: "Sensitive to Criticism", description: "They internalise critique deeply, even when it is minor or poorly delivered." },
    { title: "Resistant to Non-Traditional Paths", description: "They can mistake familiar ways for correct ways and be slow to accept different choices, even in the people they love." },
    { title: "Avoids Conflict", description: "They may smooth over issues to preserve harmony, letting real problems fester unaddressed." },
  ],
  stressTriggers: [
    "Conflict or distance inside a close family, team, or community",
    "Being taken for granted by the very people they care for",
    "Harsh or public criticism, especially of their motives",
    "Disruption to traditions or routines that matter to them",
    "Feeling unneeded or invisible",
    "Having to make decisions that will disappoint people they love",
    "Working for cold, transactional organisations",
  ],
  stressSigns: [
    "Uncharacteristic pessimism and worst-case thinking",
    "Obsessive overthinking and self-criticism",
    "Withdrawing from the very people they usually nurture",
    "Physical symptoms — exhaustion, headaches, insomnia",
    "Becoming unusually controlling or rigid",
    "Martyrdom — continuing to give while deeply resenting everyone",
  ],
  recoveryStrategies: [
    "A full block of alone time away from all demands",
    "One honest conversation with someone who cares for them for once",
    "Return to a comforting routine — familiar music, food, environments",
    "Physical movement — a walk, a swim, something gentle",
    "Write down what they actually feel, not what everyone else needs",
  ],
  socialBattery: 75,
  relationships: {
    narrative: "ESFJs love openly, attentively, and with real daily care. They commit seriously and work hard to maintain the relationship. They remember the small things, plan the anniversaries, and hold the home together across every season. Their challenge is that they can pour themselves entirely into the partner and then feel hollow when care does not flow back evenly. They need a partner who consistently notices them, expresses appreciation, and invites them to have needs of their own.",
    offers: ["Warm, attentive love expressed every day", "A partner who remembers everything and plans thoughtfully", "A stable, loving home where both of you feel at rest"],
    needs: ["A partner who actively sees and appreciates them", "Reassurance and verbal affirmation — not only actions", "Shared values and commitment to the relationship as a project"],
    challenges: ["Tend to over-give and quietly resent it later", "Can take any criticism as a sign they are failing the relationship", "May struggle to respect a partner's path if it breaks from tradition"],
    compatibleWith: [
      { type: "ISTP", reason: "A calm, competent partner whose quiet warmth balances the ESFJ's expressive care" },
      { type: "ISFP", reason: "A gentle, values-driven partner who receives the ESFJ's care with real appreciation" },
      { type: "ESTJ", reason: "A fellow organiser who shares the ESFJ's values of commitment and tradition" },
    ],
  },
  friendships: {
    narrative: "ESFJs are the friends who actually keep the group together — hosting, checking in, remembering the birthdays, making sure nobody is forgotten. Their friendship is warm, attentive, and generously organised. The main risk is that they carry more of the group's emotional and logistical work than any single person should, and burn out quietly.",
    positives: ["The friend who hosts the gathering that becomes a tradition", "The friend who notices you are struggling and brings dinner without being asked", "The friend who remembers every detail about your parents, your work, your life"],
    watchOuts: ["Can become hurt when their giving is not matched by their friends", "May push a little too hard on friends who choose unconventional paths"],
  },
  career: {
    narrative: "ESFJs thrive in people-facing, structured, caring work. They excel in nursing, teaching, people management, customer success, hospitality, and any role where attention to individuals matters. They struggle in cold, purely analytical, or ruthlessly political environments that strip out the human layer.",
    bestCareers: [
      { label: "Teacher", icon: "graduation-cap" },
      { label: "Nurse / Healthcare Professional", icon: "briefcase" },
      { label: "HR / People Lead", icon: "briefcase" },
      { label: "Event Planner", icon: "clipboard-list" },
      { label: "Customer Success Lead", icon: "briefcase" },
      { label: "Office Manager", icon: "briefcase" },
      { label: "Hospitality Manager", icon: "briefcase" },
      { label: "Family Therapist", icon: "briefcase" },
    ],
    leadershipStyle: ["Leads by caring visibly about each team member", "Builds cohesive, loyal, stable teams", "Holds high standards gently and publicly praises good work", "Can struggle with hard, people-hurting decisions"],
    asTeammate: ["The person who keeps the team humanly healthy", "Organises the logistics nobody else wants to touch", "Notices who is being left out and makes room for them"],
    cautionCareers: ["Highly isolated, purely analytical roles with little human contact", "Cutthroat commission-only or zero-sum competitive environments"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "Your twenties are the decade of using your warmth publicly while learning a crucial skill: protecting it. Build the boundary muscle early. You will keep being generous your whole life — the question is whether you give from overflow or from fumes." },
    { phase: "In Your 30s", description: "Your care is established; now the task is depth over breadth. Invest the biggest attention in the smallest number of people, and notice your own needs before everyone else's. Learn to receive care, not just give it." },
    { phase: "Midlife", description: "Your inferior Thinking function begins to surface. You may develop unexpected interest in analysis, strategy, and systematic thinking. Welcome it; it makes your care more precise and less emotionally dependent." },
    { phase: "Mature Expression", description: "At your best, you become the beloved elder whose long life of warmth has shaped entire communities. You finally let yourself receive the care you have given for decades." },
  ],
  topGrowthChallenges: ["Ask for what you need out loud — the people you love cannot read your mind", "When someone takes a path different from your tradition, lead with curiosity, not correction", "Build routines that refill you: solitude, rest, honest self-reflection"],
  famousPeople: [
    { name: "Taylor Swift", role: "Musician", reason: "Warm, community-building, attentive to her fan relationships and traditions" },
    { name: "Jennifer Garner", role: "Actress", reason: "Warm, organised, known for family-centred and community-centred living" },
    { name: "Hugh Jackman", role: "Actor", reason: "Warm, gracious, famously kind, attentive to the people around him" },
    { name: "Sarah, Duchess of York", role: "Royal", reason: "Expressive warmth, community work, devotion to family" },
    { name: "Sally Field", role: "Actress", reason: "Emotionally accessible, warm, widely-beloved through a long career" },
    { name: "Molly Weasley", role: "Fictional (Harry Potter)", reason: "Fiercely loving family matriarch who holds her people together" },
    { name: "Monica Geller", role: "Fictional (Friends)", reason: "Organised, caring, the host who holds the friend group together" },
  ],
  typeComparisons: [
    {
      vsType: "ISFJ",
      sharedTraits: ["Both Fe-plus-Si types", "Warm, loyal, service-oriented", "Remember people's details"],
      keyDifferences: ["ESFJs recharge through people and work openly; ISFJs recharge alone and work quietly", "ESFJs host whole groups; ISFJs serve one person at a time", "ESFJs express; ISFJs observe"],
      youMightBeThis: "If large groups drain you and you do your best caring work one-on-one or quietly behind the scenes",
    },
    {
      vsType: "ENFJ",
      sharedTraits: ["Both Fe-dominant", "People-focused, warm, community-building", "Attuned to emotional fields"],
      keyDifferences: ["ESFJs are grounded in present reality and tradition (Si); ENFJs are pulled by long-range vision (Ni)", "ESFJs maintain the community that exists; ENFJs imagine and build the community that could be", "ESFJs host; ENFJs mentor"],
      youMightBeThis: "If you are constantly pulled by a long-range vision for what a group or person could become",
    },
  ],
  affirmations: ["I can give deeply and still protect the well I give from.", "My worth is not measured by how much I am needed.", "Receiving love is part of how I keep giving it."],
};
