import type { PremiumTypeData } from '../premiumTypeData';

export const ESFP: PremiumTypeData = {
  code: "ESFP",
  name: "The Performer",
  tagline: "Lighting up a room and making an ordinary moment unforgettable",
  accentColor: "hsl(50 90% 55%)",
  traits: ["Extraverted", "Observant", "Feeling", "Perceiving"],
  famousQuote: { text: "You only live once, but if you do it right, once is enough.", person: "Often attributed to performers of the ESFP mold" },
  introduction: [
    "ESFPs are the warm, bright, full-of-life performers of the type world. They bring people together, turn ordinary moments into celebrations, and have an almost physical gift for lifting the mood of any room they enter.",
    "ESFPs approach life through feeling and sensation. They are generous, spontaneous, and unafraid of emotion. They trust what they sense and feel right now, more than any abstract theory about how things are supposed to be.",
    "ESFPs focus on the present. They notice mood, beauty, music, food, movement, and the small sensory details that make a moment feel alive. They tend to be warm, expressive, generous, and surprisingly perceptive about what people around them need.",
    "ESFPs are usually gifted performers, hosts, caregivers, designers, and community-builders. They thrive in work that combines real-time presence with genuine human contact, and they can turn even small interactions into something memorable.",
    "Because ESFPs live so fully on the surface of life, others sometimes underestimate the depth underneath. Under the sparkle is a Fi-driven inner compass that is non-negotiable. They will walk away from situations that violate their values, even when it costs them money, status, or security.",
    "Others see ESFPs as fun, generous, emotionally available, and sometimes dramatic. Inside their close circle they are loyal, protective, and surprisingly perceptive. They need freedom, beauty, and genuine love and will quietly wilt in environments that strip those out.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Extraverted Sensing", abbr: "Se", description: "Your primary mode. You live in high-definition contact with the physical and social present. Music, beauty, movement, atmosphere — you perceive and respond to them more intensely than most people." },
    auxiliary: { name: "Introverted Feeling", abbr: "Fi", description: "Your support system. Behind the performance is a private, serious set of values that guides every real decision. It is why your warmth is not just social skill." },
    tertiary: { name: "Extraverted Thinking", abbr: "Te", description: "Developing with age. Over time you build more structure, follow-through, and strategic thinking. It turns your gifts into durable careers and stable lives." },
    inferior: { name: "Introverted Intuition", abbr: "Ni", description: "Your hidden edge and stress trigger. Long-range speculation and abstract forecasting do not come naturally. Under heavy stress you may fixate on vague worst-case futures or become uncharacteristically paranoid." },
  },
  strengths: [
    { title: "Lifting Others", description: "ESFPs walk into a room and the mood rises. Their warmth and presence are a real gift." },
    { title: "Present-Moment Aliveness", description: "They extract joy from ordinary days. Small pleasures, attended to fully, become something bigger in their hands." },
    { title: "Generous Connection", description: "They give freely — attention, affection, help, hospitality. Their love language is open-handed." },
    { title: "Values Under the Sparkle", description: "Their warmth rests on a serious inner compass. They do not compromise on what they truly believe." },
    { title: "Adaptable and Resilient", description: "They roll with changing plans, difficult people, and hard seasons. Their bounce-back is real." },
    { title: "Reading People", description: "They notice who is struggling, who is quietly thriving, and who feels left out — and they act on what they notice." },
  ],
  weaknesses: [
    { title: "Avoids Hard Planning", description: "Long-term strategy and tedious logistics drain them. They may miss compounding opportunities as a result." },
    { title: "Sensitive to Criticism", description: "Their openness means critique lands harder than it is meant. They can spiral over feedback that was minor." },
    { title: "Struggles With Conflict", description: "They want everyone to be OK and can smooth over real issues rather than address them directly." },
    { title: "Impulsive With Money and Commitments", description: "Present-moment energy can lead to choices that their future self has to manage." },
    { title: "Difficulty With Alone-Time", description: "Extended solitude can leave them low and doubting themselves. They can become dependent on external stimulation." },
  ],
  stressTriggers: [
    "Harsh or public criticism, especially of their character",
    "Long stretches of isolation or solitary work",
    "Being trapped in cold, transactional, or values-empty environments",
    "Constant emotional conflict inside their close circle",
    "Loss of freedom, creativity, or sensory richness in daily life",
    "Being mocked or dismissed for their expressiveness",
    "Pressure to commit to long-term plans they have not felt into",
  ],
  stressSigns: [
    "Uncharacteristic brooding and dark, worst-case thinking",
    "Fixating on vague future fears rather than staying in the present",
    "Impulsive spending, eating, or escape behaviours",
    "Withdrawing from the people they usually energise",
    "Becoming brittle and unusually quiet",
    "Self-doubt that spirals into self-criticism",
  ],
  recoveryStrategies: [
    "Time with one or two people who love them exactly as they are",
    "Physical movement — dance, sport, walking, anything that returns them to the body",
    "A sensory reset — beautiful music, food, a beloved place",
    "Creative self-expression with no outcome attached",
    "Short break from screens and other sources of second-hand emotion",
  ],
  socialBattery: 90,
  relationships: {
    narrative: "ESFPs love warmly, openly, and in the present tense. They commit when the connection is real and show love through affection, attention, shared experience, and countless small generous gestures. The challenge is that they can avoid the harder conversations in favour of keeping the mood good, and they may struggle in long quiet seasons when the performance of love has to become the patience of love. They need a partner who sees the depth beneath the sparkle and stays present when life gets heavy.",
    offers: ["Warm, expressive, fully-embodied love every day", "A partner who brings joy, spontaneity, and real sensory aliveness", "Generous devotion under the sparkle"],
    needs: ["A partner who honours their values and respects their emotional openness", "Real connection, not transactional partnership", "Gentle reassurance when they doubt themselves"],
    challenges: ["Can avoid difficult conversations to preserve the good mood", "May struggle with long-term financial or logistical planning", "Sensitive to criticism in ways that can derail a hard talk"],
    compatibleWith: [
      { type: "ISTJ", reason: "A steady, reliable partner who anchors the ESFP while honouring their aliveness" },
      { type: "INTJ", reason: "A deep, structured counterpart whose inner world the ESFP loves drawing out" },
      { type: "ISFP", reason: "A fellow Se-plus-Fi type who shares the sensory, values-driven way of living" },
    ],
  },
  friendships: {
    narrative: "ESFPs are warm, generous, fully-present friends. They remember your favourite drink, show up at your door when you are hurting, and make every gathering feel like it matters. Their friendship is energetic and tender, and they will prioritise the people they love above almost anything else.",
    positives: ["The friend who makes every shared hour feel a little more like life", "The friend who reads your mood accurately and meets it", "The friend who organises the trip that ends up being the best memory of the year"],
    watchOuts: ["Can over-absorb a friend's pain and carry it home", "May avoid difficult honesty in favour of keeping the friendship pleasant"],
  },
  career: {
    narrative: "ESFPs thrive in people-facing, expressive, sensory-rich work. They excel in performance, hospitality, design, sales, teaching, healthcare, and community roles. They struggle in cold, analytical, isolated environments or in bureaucracies that strip out the human layer. The ideal ESFP role has real contact with people, aesthetic engagement, and some creative expression.",
    bestCareers: [
      { label: "Performer / Actor", icon: "briefcase" },
      { label: "Event Planner", icon: "clipboard-list" },
      { label: "Flight Attendant", icon: "briefcase" },
      { label: "Nurse", icon: "briefcase" },
      { label: "Personal Trainer", icon: "briefcase" },
      { label: "Interior Designer", icon: "briefcase" },
      { label: "Sales Professional", icon: "briefcase" },
      { label: "Hospitality / Restaurateur", icon: "briefcase" },
    ],
    leadershipStyle: ["Leads through warmth, example, and keeping the team genuinely alive", "Celebrates wins openly and creates real belonging", "Prefers flat, close-knit teams over hierarchical distance", "Can struggle with long-term strategic planning and hard disciplinary decisions"],
    asTeammate: ["The person who keeps morale high when pressure rises", "Notices who is being left out and pulls them in", "Turns even a grind into something the team can enjoy"],
    cautionCareers: ["Long-cycle solitary research or theoretical work", "Cold, rigid bureaucracies with little human contact"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "Your twenties are the decade of leaning into your warmth and presence while learning a crucial skill: planning for the future. Build enough financial and logistical structure to protect the freedom you love. Take your creative gifts seriously enough to practice them consistently." },
    { phase: "In Your 30s", description: "Your gifts are known; now the task is compounding them. Pick a craft, a career, or a commitment and stay past the moment it gets boring. Pair a steady operator — or steady habits — with your natural spark." },
    { phase: "Midlife", description: "Your inferior Intuition function begins to surface. You may find yourself unexpectedly drawn to meaning, legacy, and long-range purpose. Welcome it; it gives your natural aliveness a destination worth reaching." },
    { phase: "Mature Expression", description: "At your best, you become the beloved elder whose warmth has accumulated into real wisdom. Your life is as generous as it always was, but now it has depth, reliability, and long-term impact people can point to." },
  ],
  topGrowthChallenges: ["Stay with the long, quiet seasons; depth is on the other side of the plateau", "Have the hard honest conversation early; the kindness is in the honesty, not the avoidance", "Build routines that protect your own inner life, not just your outer sparkle"],
  famousPeople: [
    { name: "Elvis Presley", role: "Musician", reason: "Electric stage presence; turned performance into a cultural force" },
    { name: "Hibari Misora", role: "Singer & actress", reason: "Magnetic performer whose warmth and presence captivated audiences for decades" },
    { name: "Marilyn Monroe", role: "Actress", reason: "Warm, vulnerable, radiant on and off screen" },
    { name: "Jamie Oliver", role: "Chef", reason: "Warm, expressive, turns cooking into connection and celebration" },
    { name: "Serena Williams", role: "Tennis great", reason: "Physical brilliance with generous warmth off the court" },
    { name: "Kyu Sakamoto", role: "Singer", reason: "Joyful, spontaneous performer who radiated charm on stage and screen" },
    { name: "Will Smith", role: "Actor", reason: "Charismatic, emotionally open, made a career of warm presence" },
    { name: "Peregrin Took", role: "Fictional (LOTR)", reason: "Warm, spontaneous, brave once committed to his friends" },
    { name: "Rachel Green", role: "Fictional (Friends)", reason: "Warm, expressive, grew from sparkle into real depth over time" },
  ],
  typeComparisons: [
    {
      vsType: "ISFP",
      sharedTraits: ["Both Se-plus-Fi types", "Present-focused, values-driven, sensory", "Authentic and warm"],
      keyDifferences: ["ESFPs recharge in public; ISFPs recharge alone", "ESFPs perform; ISFPs create quietly", "ESFPs show up in the moment; ISFPs show up in the work"],
      youMightBeThis: "If you do your best caring in quiet one-to-one moments and feel drained by crowds",
    },
    {
      vsType: "ENFP",
      sharedTraits: ["Both extraverts with strong Fi", "Warm, expressive, values-driven", "Social catalysts"],
      keyDifferences: ["ESFPs are grounded in the senses and the present (Se); ENFPs live in possibilities and ideas (Ne)", "ESFPs perform in the moment; ENFPs imagine new worlds", "ESFPs do; ENFPs dream"],
      youMightBeThis: "If your inner life runs on ideas and possibility more than on sensory presence and what is in front of you",
    },
  ],
  affirmations: ["My warmth is real power — and it lasts longer when I pair it with structure.", "I can stay in the quiet, unglamorous seasons without losing my aliveness.", "Honest conversation is a deeper kindness than protected good vibes."],
};
