import type { PremiumTypeData } from '../premiumTypeData';

export const ESTP: PremiumTypeData = {
  code: "ESTP",
  name: "The Daredevil",
  tagline: "Seizing an opportunity in real time and turning it into a win",
  accentColor: "hsl(25 85% 50%)",
  traits: ["Extraverted", "Observant", "Thinking", "Perceiving"],
  famousQuote: { text: "Fortune favours the bold.", person: "Often attributed to daredevils of the ESTP mold" },
  introduction: [
    "ESTPs are the bold, action-oriented closers of the type world. They are electric in a live situation — negotiations, emergencies, fast-moving deals, competitive contests — and they read a real-time environment faster than almost anyone else.",
    "ESTPs approach life pragmatically and energetically. They trust what is in front of them, back themselves to figure it out on the fly, and have little patience for theory that cannot be tested against reality right now.",
    "ESTPs focus on the present. They notice movement, force, opportunity, and the small cues that tell them what is really happening. They tend to be observant, direct, competitive, and remarkably resilient under pressure that would break other types.",
    "ESTPs are usually excellent entrepreneurs, sales leaders, negotiators, emergency responders, athletes, and operators in any high-tempo, high-stakes environment. They come alive in action and tend to wilt in long stretches of planning or theory.",
    "Because ESTPs move fast and speak plainly, others sometimes mistake them for reckless or shallow. In reality there is usually a sharp analytical mind running underneath the energy, making real-time Ti calculations that others only see as confidence.",
    "Others see ESTPs as charismatic, bold, playful, and sometimes intimidating. Inside their small circle they are loyal, fun, and unexpectedly protective. They take action-shaped loyalty seriously and will show up hard for the people they have chosen.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Extraverted Sensing", abbr: "Se", description: "Your primary mode. You are tuned to the immediate physical world in high definition — opportunity, danger, movement, signal. You read a room, a field, or a situation faster than most people can think about it." },
    auxiliary: { name: "Introverted Thinking", abbr: "Ti", description: "Your support system. Behind the improvisation is a sharp internal logic that cuts through nonsense and spots the real mechanism. It is why your instincts hold up under pressure." },
    tertiary: { name: "Extraverted Feeling", abbr: "Fe", description: "Developing with age. Over time you grow more attuned to group mood and long-term relationship maintenance. It softens the action-first edge into real leadership." },
    inferior: { name: "Introverted Intuition", abbr: "Ni", description: "Your hidden edge and stress trigger. Long-range strategic speculation is not home. Under heavy stress you may fixate on unlikely future catastrophes or become unusually superstitious." },
  },
  strengths: [
    { title: "Real-Time Awareness", description: "ESTPs notice everything — faces, body language, environment, signal. Their perception is unusually sharp in the moment." },
    { title: "Bold Decision-Making", description: "They commit quickly and are rarely paralysed. Their willingness to act while others hesitate gives them real edge." },
    { title: "Pressure-Tested Calm", description: "High-stakes situations are where they shine. Emergencies, negotiations, and competitive moments pull out their best." },
    { title: "Charisma and Persuasion", description: "They can sell, close, negotiate, and connect. Their energy pulls people toward them." },
    { title: "Adaptable and Resilient", description: "Plans change constantly and ESTPs are fine with it. They pivot in real time without losing momentum." },
    { title: "Practical Problem-Solving", description: "They cut through theory and focus on what will actually work right now. Their hands-on competence is real." },
  ],
  weaknesses: [
    { title: "Impatient With Theory", description: "They can dismiss long-term planning and strategic reflection as overthinking, missing important considerations." },
    { title: "Risk-Seeking", description: "Their appetite for action can lead to choices that feel right in the moment but cost them badly later." },
    { title: "Struggles With Routine", description: "Long maintenance work and repetitive administration drain them fast." },
    { title: "Blunt and Sometimes Insensitive", description: "They say what they see and can hurt feelings without noticing." },
    { title: "Short-Term Bias", description: "They can chase immediate wins at the expense of compounding long-term bets." },
  ],
  stressTriggers: [
    "Long stretches of static, routine, boring work",
    "Heavy bureaucracy that prevents real-time problem solving",
    "Being trapped in theoretical discussions with no path to action",
    "Micromanagement from people they consider less competent",
    "Prolonged emotional processing with no movement",
    "Loss of physical freedom or autonomy",
    "Environments that punish boldness and reward compliance",
  ],
  stressSigns: [
    "Uncharacteristic brooding and dark, catastrophic thinking",
    "Obsessing over a single possible future and losing present flexibility",
    "Impulsive, risky behaviour — speed, spending, substances",
    "Withdrawing from the very people they usually energise",
    "Sudden fixation on a distant goal at the expense of current reality",
    "Becoming brittle, defensive, or uncharacteristically paranoid",
  ],
  recoveryStrategies: [
    "Hard physical activity — sport, training, real exertion",
    "Change of venue — a trip, a new city, a new environment",
    "One honest, direct conversation with a trusted friend",
    "Short, high-stakes project that pulls them into flow",
    "Simplify the inputs — fewer meetings, fewer decisions, more action",
  ],
  socialBattery: 85,
  relationships: {
    narrative: "ESTPs love with energy, playfulness, and bold presence. They commit when the fit is real and show love through shared adventure, protective loyalty, and physical affection. The challenge is that they can grow bored in the steady, maintenance phase of a relationship or dodge the deeper emotional conversations. They need a partner who can match their intensity, pull them into depth when needed, and stay unfazed by their bluntness.",
    offers: ["A partner who keeps life exciting and brings real energy into every day", "Fierce protective loyalty once they have chosen you", "A confident, capable partner for every kind of challenge"],
    needs: ["A partner who can match their pace and bring their own fire", "Directness — hints and subtle signals will be missed", "Freedom to act, explore, and not feel caged"],
    challenges: ["Can dodge deep emotional conversations in favour of action", "May struggle in the quiet, steady phase of a long relationship", "Their bluntness can land harshly without intent"],
    compatibleWith: [
      { type: "ISFJ", reason: "A warm, attentive partner who anchors the ESTP and decodes their restless energy" },
      { type: "ISTJ", reason: "A steady counterpart whose reliability balances the ESTP's spontaneity" },
      { type: "ESFP", reason: "A fellow Se-dominant who shares the love of action and sensory aliveness" },
    ],
  },
  friendships: {
    narrative: "ESTPs are fun, loyal, unexpectedly generous friends. They are often the instigator of the adventure, the one who calls to turn a normal Wednesday into something memorable. Their friendship is energetic and protective, and they will drop plans to help a friend in a real emergency.",
    positives: ["The friend who turns a quiet weekend into a story you will tell for years", "The friend who will show up fast when something actually goes wrong", "The friend whose confidence and humour pull you through tough weeks"],
    watchOuts: ["Can be blunt in ways that wound without intent", "May lose interest in friends who cannot match their pace"],
  },
  career: {
    narrative: "ESTPs thrive in high-tempo, high-stakes, results-oriented roles. They excel in sales, entrepreneurship, trading, emergency response, sports, performance, and any environment that rewards real-time decisions and bold action. They struggle in low-stakes, bureaucratic, theoretical environments where nothing moves and no one commits.",
    bestCareers: [
      { label: "Entrepreneur / Founder", icon: "briefcase" },
      { label: "Sales Leader", icon: "briefcase" },
      { label: "Trader", icon: "bar-chart" },
      { label: "Paramedic / Firefighter", icon: "shield" },
      { label: "Professional Athlete / Coach", icon: "briefcase" },
      { label: "Trial Lawyer", icon: "scale" },
      { label: "Military Officer", icon: "shield" },
      { label: "Real Estate Developer", icon: "building" },
    ],
    leadershipStyle: ["Leads from the front — takes the risk first and trusts the team to follow", "Makes decisions in real time, refuses to be paralysed by analysis", "Rewards boldness and results over process and ceremony", "Can neglect long-range strategic planning and quiet team maintenance"],
    asTeammate: ["The person who actually closes the deal, runs the crisis, takes the shot", "Keeps team energy high under pressure", "Says what everyone else is thinking and acts on it immediately"],
    cautionCareers: ["Long-cycle academic research or pure theory roles", "Highly bureaucratic, ceremony-heavy organisations"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "Your twenties are the decade of controlled boldness. Take the risks that compound, not just the ones that feel exciting. Learn to pair your boldness with just enough strategic patience to let your wins build on each other." },
    { phase: "In Your 30s", description: "Your track record is real now; the frontier is depth. Pick the arena you want to dominate and commit past the point where it gets boring. Invest in relationships that outlast any single deal or adventure." },
    { phase: "Midlife", description: "Your inferior Intuition function begins to open. You may find yourself unexpectedly drawn to long-range vision, meaning, and legacy. Welcome it; it gives your natural drive a destination worth hitting." },
    { phase: "Mature Expression", description: "At your best, you become the bold, wise operator whose decades of real-world wins have been matched by hard-won depth. Your advice is sought precisely because you have actually lived the decisions." },
  ],
  topGrowthChallenges: ["Before you act, ask where this still matters in five years", "Stay in the quiet seasons of a relationship; the reward is on the other side of the plateau", "Let yourself feel what you feel — suppressing it just pushes it into the body"],
  famousPeople: [
    { name: "Ernest Hemingway", role: "Writer", reason: "Lived hard, wrote lean, pursued experience as the raw material" },
    { name: "Toyotomi Hideyoshi", role: "Warlord & unifier of Japan", reason: "Bold, opportunistic, action-first leader who climbed from foot soldier to ruler" },
    { name: "Madonna", role: "Musician", reason: "Bold, reinventing, risk-taking career across decades" },
    { name: "Bruce Willis", role: "Actor", reason: "Cool-headed action presence with a dry wit" },
    { name: "Eddie Murphy", role: "Comedian & actor", reason: "Electric, improvisational, unafraid of the crowd" },
    { name: "Rikidōzan", role: "Pro wrestler", reason: "Charismatic showman who turned raw physicality and presence into national stardom" },
    { name: "Winston Churchill", role: "UK Prime Minister", reason: "Bold, pragmatic, decisive in wartime crisis" },
    { name: "Han Solo", role: "Fictional (Star Wars)", reason: "Improvisational, charming, bold under pressure" },
    { name: "Jack Sparrow", role: "Fictional (Pirates of the Caribbean)", reason: "Clever, opportunistic, thrives in chaos" },
  ],
  typeComparisons: [
    {
      vsType: "ESFP",
      sharedTraits: ["Both Se-dominant", "Present-focused, action-oriented, socially electric", "Love novelty"],
      keyDifferences: ["ESTPs lead with logic (Ti); ESFPs lead with values (Fi)", "ESTPs compete and close; ESFPs perform and connect", "ESTPs argue the deal; ESFPs read the room"],
      youMightBeThis: "If your gut first move is to connect emotionally and make people feel great, rather than to analyse and close",
    },
    {
      vsType: "ENTP",
      sharedTraits: ["Both extraverts", "Fast thinkers, persuasive, allergic to boredom", "Adaptable in the moment"],
      keyDifferences: ["ESTPs live in the physical present (Se); ENTPs live in the world of ideas (Ne)", "ESTPs do; ENTPs theorise", "ESTPs trust the senses; ENTPs trust the pattern"],
      youMightBeThis: "If you find yourself constantly generating abstract ideas rather than acting on what is in front of you",
    },
  ],
  affirmations: ["My boldness is real power when I pair it with patience and long-range care.", "I can stay in the quiet seasons without losing my fire.", "Feeling what I feel is not weakness — it is the missing half of my strength."],
};
