import type { PremiumTypeData } from '../premiumTypeData';

export const INFJ: PremiumTypeData = {
  code: "INFJ",
  name: "The Visionary",
  tagline: "Inspiring others to work toward a shared, meaningful vision",
  accentColor: "hsl(195 55% 50%)",
  traits: ["Introverted", "Intuitive", "Feeling", "Judging"],
  famousQuote: { text: "The purpose of life is not to be happy. It is to be useful, to be honourable, to be compassionate, to have it make some difference that you have lived and lived well.", person: "Often attributed to visionaries of the INFJ mold" },
  introduction: [
    "INFJs are the rarest of the types — quiet, idealistic, and deeply attuned to the inner lives of other people. They live for meaning. A career, a relationship, or an idea that does not carry moral weight for them will not hold them for long.",
    "INFJs approach life through a mix of strong intuition and deep empathy. They perceive more about other people than they usually let on, and they hold a private sense of the way things should be that guides everything they do.",
    "INFJs focus on the long view — the future they want to help bring into being, the person someone is becoming, the pattern under the present moment. They tend to be insightful, principled, creative, and quietly determined.",
    "INFJs are usually excellent counsellors, mentors, and writers because they combine deep insight with real care. They can see the next move in a person's life long before they see it themselves, and they know how to gently point at it without pushing.",
    "Because INFJs process so much internally, others often mistake them for shy or passive. In reality they are decisive about what matters and will hold their ground on principle with surprising firmness. Their softness is not weakness.",
    "Others see INFJs as thoughtful, gentle, private, and sometimes mysterious. Inside their small circle they are warm, loyal, and deeply committed. They need substantial solitude to stay themselves and will quietly withdraw from relationships that demand constant performance.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Introverted Intuition", abbr: "Ni", description: "Your primary mode. You receive meaning, symbolism, and long-range implication in flashes. You often know where a situation or a person is heading long before any data has been laid out." },
    auxiliary: { name: "Extraverted Feeling", abbr: "Fe", description: "Your support system. You tune into the emotional field of a group and adjust yourself to help it function. This is how your inner vision reaches other people — through care, not argument." },
    tertiary: { name: "Introverted Thinking", abbr: "Ti", description: "Developing with age. Over time you bring more logical rigor to your intuitions, pressure-testing them before acting. It makes your insights more credible and harder to dismiss." },
    inferior: { name: "Extraverted Sensing", abbr: "Se", description: "Your hidden edge and stress trigger. The immediate, physical present is not your home. Under heavy stress you may lurch into impulsive sensory behaviour — overeating, overspending, reckless escape." },
  },
  strengths: [
    { title: "Deep Insight into People", description: "INFJs perceive motives, patterns, and emotional undercurrents that most people never notice. They often know what is wrong in a room before anyone speaks." },
    { title: "Principled Conviction", description: "They act from a clear inner compass. Once an INFJ decides something is right, they hold that ground even when it costs them socially or professionally." },
    { title: "Empathic Without Losing Self", description: "At their best, they can feel deeply with another person without dissolving into that person's state. This is rare and powerful." },
    { title: "Visionary Thinking", description: "They can see a different future clearly enough to describe it. They are the type most likely to articulate a shared direction others can actually feel." },
    { title: "Quiet Determination", description: "INFJs do not push loudly, but they rarely quit. Their long arc of steady commitment tends to outlast louder, more dramatic energy." },
    { title: "Powerful Writers and Communicators", description: "Given time, they produce language that moves people. Their combination of empathy, vision, and precision is distinctive." },
  ],
  weaknesses: [
    { title: "Prone to Burnout", description: "Their empathy is deep and their standards are high. Without active boundaries they give until there is nothing left and collapse privately." },
    { title: "Reluctant to Confront", description: "They can avoid necessary conflict to preserve harmony, letting small resentments build into full internal fractures." },
    { title: "Perfectionist", description: "Nothing feels good enough. This can paralyse their creative work and leave them exhausted by their own impossible standards." },
    { title: "Can Be Stubbornly Idealistic", description: "When an INFJ has decided the moral shape of a situation, they can resist evidence that complicates it." },
    { title: "Private to a Fault", description: "They share so little of their inner experience that partners and friends end up guessing, and the INFJ ends up lonely inside the relationship." },
  ],
  stressTriggers: [
    "Being in prolonged interpersonal conflict or emotional tension",
    "Environments that demand performative extraversion for long stretches",
    "Working for organisations whose values clash with their own",
    "Being misunderstood or mischaracterised in ways they cannot correct",
    "Taking on other people's emotions without space to process their own",
    "Having no creative outlet or quiet thinking time",
    "Feeling trapped in a role, relationship, or place that violates their values",
  ],
  stressSigns: [
    "Withdrawing completely from people they usually love",
    "Uncharacteristic physical impulsivity — overeating, overspending, drinking",
    "Cynicism and harsh judgement of themselves and others",
    "Sleep disruption and physical symptoms that seem to come from nowhere",
    "Ruminating endlessly over past interactions and perceived failures",
    "Becoming brittle, snappy, and emotionally raw in daily interactions",
  ],
  recoveryStrategies: [
    "Deliberate solitude — days if needed, not just an evening",
    "Creative expression: writing, journaling, art, music",
    "Time in nature, ideally quiet and unstructured",
    "One long honest conversation with a trusted, non-draining person",
    "Physical movement that pulls them out of the head and into the body",
  ],
  socialBattery: 20,
  relationships: {
    narrative: "INFJs seek deep, meaningful partnership — not casual companionship. They commit slowly but profoundly and can read a partner's inner state with uncanny accuracy. They express love through presence, attention, and acts of quiet devotion. Their great risk is giving too much while revealing too little, ending up resentful and unseen. They need a partner who can be emotionally honest, handle real depth, and reassure them that their inner world is welcome, not a burden.",
    offers: ["Unusual emotional attunement and true understanding", "Deep, committed loyalty once they have chosen you", "A private inner world they will let you into if you earn it"],
    needs: ["Emotional depth and honest, real conversation", "Time alone that is not treated as rejection", "A partner who stays steady when they are quietly overwhelmed"],
    challenges: ["May hide needs and resentments until they boil over", "Can idealise a partner and struggle when reality intrudes", "Tend to absorb a partner's emotions and lose themselves"],
    compatibleWith: [
      { type: "ENTP", reason: "Playful energy that pulls the INFJ out of their head without overwhelming them" },
      { type: "ENFP", reason: "A warm, curious partner who meets them in depth and brings joyful spark" },
      { type: "INTJ", reason: "A rare fellow Ni-type who understands the inner vision without explanation" },
    ],
  },
  friendships: {
    narrative: "INFJs are rare friends who offer unusual depth and attention. They have very few close friends by design, and those friends are treated almost like family. They can be inconsistent about social contact — present one month, absent the next — but within the friendships that matter, they are profoundly loyal.",
    positives: ["The friend who remembers what you said three years ago and brings it up exactly when you need it", "The friend who names the thing you had not dared to name yet", "The friend whose advice is gentle, careful, and quietly transformative"],
    watchOuts: ["Can withdraw suddenly and leave friends wondering what they did wrong", "May internalise a friend's problem until it becomes their own stress"],
  },
  career: {
    narrative: "INFJs thrive where meaning, people, and creativity meet. They do their best work in roles that let them help individuals, shape culture, or articulate a vision that matters to them morally. They are miserable in transactional, values-empty environments — regardless of the pay. Autonomy, depth, and alignment with their inner compass are non-negotiable.",
    bestCareers: [
      { label: "Psychologist / Therapist", icon: "briefcase" },
      { label: "Writer", icon: "briefcase" },
      { label: "Human Rights Advocate", icon: "briefcase" },
      { label: "Teacher / Professor", icon: "graduation-cap" },
      { label: "Non-Profit Leader", icon: "briefcase" },
      { label: "Counsellor", icon: "briefcase" },
      { label: "UX Researcher", icon: "briefcase" },
      { label: "Spiritual or Pastoral Work", icon: "briefcase" },
    ],
    leadershipStyle: ["Leads by articulating a vision people can believe in", "Invests heavily in the people they lead, one by one", "Prefers collaborative, values-aligned teams over hierarchy", "Can struggle with hard operational decisions that hurt individuals"],
    asTeammate: ["The person who notices when a teammate is quietly struggling", "Connects the team's work back to the deeper purpose", "Prefers fewer, deeper conversations to broad networking"],
    cautionCareers: ["High-volume sales quotas (conflicts with their values orientation)", "Cutthroat, zero-sum environments that reward ruthless competition"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "Your twenties are the decade of learning what you actually believe — not what you absorbed. Take on roles that test your values under pressure. Build the boundary muscle; you will need it for the rest of your life." },
    { phase: "In Your 30s", description: "This is the decade to translate inner vision into durable external work. Write the book, start the practice, build the institution. Pair your depth with enough structure to let it reach people reliably." },
    { phase: "Midlife", description: "Your inferior Sensing function starts to open. You may find unexpected pleasure in the body, the garden, food, simple physical presence. Lean into it; it keeps you from living entirely in your head." },
    { phase: "Mature Expression", description: "At your best, you become the quiet elder whose life has clearly served something larger than itself. People come to you for the clarity your long inner work has produced." },
  ],
  topGrowthChallenges: ["Say the hard thing sooner — withheld truth becomes slow-burning resentment", "Protect your energy: a clear no is a deeper kindness than a reluctant yes", "Share your inner world out loud; the people who love you cannot read your mind"],
  famousPeople: [
    { name: "Mahatma Gandhi", role: "Civil rights leader", reason: "Quiet, principled, visionary leadership that reshaped a nation" },
    { name: "Martin Luther King Jr.", role: "Civil rights leader", reason: "Moral vision combined with extraordinary moral clarity and courage" },
    { name: "Nelson Mandela", role: "Statesman", reason: "Long-arc leader who led by principle and personal example" },
    { name: "Carl Jung", role: "Psychologist", reason: "Depth psychologist who mapped the inner life for a century of readers" },
    { name: "Jane Goodall", role: "Primatologist & activist", reason: "Patient, empathic, values-driven lifelong commitment to a single cause" },
    { name: "Dostoevsky", role: "Novelist", reason: "Psychological depth and moral seriousness at the highest literary level" },
    { name: "Atticus Finch", role: "Fictional (To Kill a Mockingbird)", reason: "Quiet, principled, morally clear in a world that was not" },
  ],
  typeComparisons: [
    {
      vsType: "INFP",
      sharedTraits: ["Both introverted, intuitive, and value-driven", "Live from a rich inner world", "Deeply caring"],
      keyDifferences: ["INFJs externalise their values through Fe, working on group harmony; INFPs hold values privately through Fi", "INFJs drive toward a vision and want closure; INFPs stay open and explore", "INFJs build; INFPs wander"],
      youMightBeThis: "If your values feel private and personal rather than something you want to organise others around",
    },
    {
      vsType: "ENFJ",
      sharedTraits: ["Both use Fe and Ni", "People-focused, purpose-driven, natural mentors", "Care intensely about others"],
      keyDifferences: ["INFJs recharge in solitude and work mostly internally; ENFJs recharge through people and work outwardly", "INFJs prefer one-to-one depth; ENFJs energise whole groups", "INFJs write the vision; ENFJs rally people around it"],
      youMightBeThis: "If you come alive in front of groups and your inner world quiets when you are surrounded by people you love",
    },
  ],
  affirmations: ["My depth is a gift — I offer insight the world genuinely needs.", "I can care for others without disappearing into their needs.", "Speaking my truth is a kindness, not a burden."],
};
