import type { PremiumTypeData } from '../premiumTypeData';

export const INFP: PremiumTypeData = {
  code: "INFP",
  name: "The Idealist",
  tagline: "Creating art or writing that moves people on a deep emotional level",
  accentColor: "hsl(330 55% 60%)",
  traits: ["Introverted", "Intuitive", "Feeling", "Perceiving"],
  famousQuote: { text: "You must be the change you wish to see in the world.", person: "Often attributed to idealists of the INFP mold" },
  introduction: [
    "INFPs are the dreamers and inner poets of the type world. They live from a private, fiercely-held set of values and seek work and relationships that let those values breathe. Authenticity is not a nice-to-have for them; it is oxygen.",
    "INFPs approach life through deep feeling and imagination. They perceive subtle emotional truths that others miss, and they care intensely about what is right — not in an abstract philosophical way, but in a deeply personal one.",
    "INFPs focus on meaning and possibility. They are drawn to symbols, stories, causes, and people who seem to carry something real. They can be gentle, idealistic, creative, and quietly stubborn about what they will and will not do.",
    "INFPs are usually exceptional writers, artists, counsellors, and advocates because they combine an inward emotional life with imaginative range. They can give voice to feelings most people cannot articulate.",
    "Because INFPs live so much in their inner world, others often underestimate their resolve. Under the softness is a spine of iron when a core value is at stake. They will walk away from prestige, money, or relationships rather than violate what matters.",
    "Others see INFPs as kind, thoughtful, sometimes dreamy, and surprisingly complex once you get past the quiet. Inside their small circle they are warm, loyal, and deeply devoted. They need real solitude to restore themselves and will quietly disappear from environments that flatten them.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Introverted Feeling", abbr: "Fi", description: "Your primary mode. You hold a rich, private value system and evaluate every situation against it. What is right for you is felt from the inside out, not borrowed from group consensus." },
    auxiliary: { name: "Extraverted Intuition", abbr: "Ne", description: "Your support system. You see possibilities, meanings, and connections everywhere. It keeps your inner values open to new ideas and fuels your creative imagination." },
    tertiary: { name: "Introverted Sensing", abbr: "Si", description: "Developing with age. Over time you draw more on personal memory, ritual, and trusted routines. It gives stability to your values-first life." },
    inferior: { name: "Extraverted Thinking", abbr: "Te", description: "Your hidden edge and stress trigger. Logistics, structure, and efficiency do not come naturally. Under heavy stress you may become uncharacteristically harsh, controlling, or critical of yourself and others." },
  },
  strengths: [
    { title: "Deep Empathy", description: "INFPs feel what others feel without needing it explained. They tend to be the person friends turn to when nothing else is working." },
    { title: "Creative Imagination", description: "Their inner world is dense with images, stories, and possibilities. Art, writing, and design are natural homes for their gift." },
    { title: "Values-Driven Integrity", description: "They do not bend their principles for convenience. You always know where an INFP actually stands on what matters." },
    { title: "Seeing People Clearly", description: "They read inner life with unusual accuracy. Under the surface of any group, an INFP is tracking the emotional truth." },
    { title: "Quiet Resilience", description: "They endure more than they let on. Their capacity to keep caring through hard seasons is a form of strength that is easy to miss." },
    { title: "Non-Judgemental Acceptance", description: "They offer space for people to be their full, messy selves — a rare gift in a judgemental world." },
  ],
  weaknesses: [
    { title: "Struggles with Structure and Logistics", description: "Deadlines, admin, and practical follow-through can drain them. They may drift in roles that reward those skills." },
    { title: "Avoids Conflict", description: "They dislike confrontation so much they may swallow genuine grievances until they spill out sideways." },
    { title: "Idealism vs Reality Gap", description: "Their picture of how things should be can make ordinary, messy reality feel disappointing and grey." },
    { title: "Over-Absorbs Emotion", description: "Without strong boundaries they take on the pain of others and pay for it privately." },
    { title: "Indecisive on Practical Matters", description: "Too many options paralyse them. They can endlessly research a choice that a more decisive type would have made in five minutes." },
  ],
  stressTriggers: [
    "Environments that violate their core values",
    "Constant criticism, especially of their character or sincerity",
    "Being forced into highly extraverted performance over long stretches",
    "Pressure to be ruthless, transactional, or emotionally fake",
    "Loud, chaotic, or high-conflict environments",
    "Having no creative or solitary outlet",
    "Feeling unseen by the people closest to them",
  ],
  stressSigns: [
    "Withdrawing into their inner world and going very quiet",
    "Uncharacteristic irritability and harsh, critical statements",
    "Obsessing over logistics and control they usually ignore",
    "Physical symptoms and sleep disruption",
    "Becoming cynical or self-loathing about their own creative work",
    "Paralysis on small decisions that normally would not stall them",
  ],
  recoveryStrategies: [
    "Real solitude — no performance, no demands, no people-pleasing",
    "Creative expression: writing, journaling, music, making something beautiful",
    "Time in nature, especially water, trees, or open sky",
    "One honest, unhurried conversation with a safe person",
    "Physical movement that returns them to the body — walks, dance, yoga",
  ],
  socialBattery: 20,
  relationships: {
    narrative: "INFPs seek soulful, meaningful partnership. They fall deeply, commit slowly, and can be wounded by casualness where they expected reverence. They show love through deep presence, small poetic gestures, and a loyalty that quietly endures. They can struggle with practical relationship logistics and with naming difficult feelings before those feelings harden. They need a partner who sees their inner life as real and treasurable, not as something to be 'gotten over'.",
    offers: ["An unusually rich inner life shared only with you", "Devoted, patient love that endures through hard seasons", "A partner who sees and celebrates who you are, not what you produce"],
    needs: ["A partner who honours their values and does not try to change them", "Real emotional depth — no performative or shallow closeness", "Time alone to refill without guilt or accusation"],
    challenges: ["May withdraw into silence rather than articulate a hurt", "Can idealise the partner early and struggle when reality arrives", "Tend to over-accommodate and then resent it later"],
    compatibleWith: [
      { type: "ENFJ", reason: "A warm, structured partner who draws the INFP out into the world gently" },
      { type: "ENTJ", reason: "A decisive, loving counterpart who handles the logistics while honouring the INFP's depth" },
      { type: "INFJ", reason: "A rare fellow introspective type who understands silence and meaning" },
    ],
  },
  friendships: {
    narrative: "INFPs are quietly devoted friends. They keep a small circle and invest in it deeply. Their friendship is not loud or constant, but it is unusually real — honest conversations, true listening, and the feeling that this person actually sees you.",
    positives: ["The friend who reads you accurately when you are pretending you are fine", "The friend whose letters, texts, or gifts carry real thought and care", "The friend who will sit with you through the hard thing without trying to fix it"],
    watchOuts: ["Can disappear for long periods when overwhelmed, without explanation", "May avoid addressing friction until resentment has built up"],
  },
  career: {
    narrative: "INFPs thrive in meaningful, creative, values-aligned work. They do their best in roles that let them give voice to something — art, writing, counselling, advocacy — and in environments where authenticity is not punished. They struggle in cut-throat, purely transactional roles or in bureaucracies whose rules feel arbitrary and soulless.",
    bestCareers: [
      { label: "Writer / Author", icon: "briefcase" },
      { label: "Counsellor / Therapist", icon: "briefcase" },
      { label: "Designer / Artist", icon: "briefcase" },
      { label: "UX Researcher", icon: "briefcase" },
      { label: "Social Worker", icon: "briefcase" },
      { label: "Librarian / Archivist", icon: "briefcase" },
      { label: "Editor", icon: "briefcase" },
      { label: "Non-Profit Program Lead", icon: "briefcase" },
    ],
    leadershipStyle: ["Leads through authenticity, example, and shared values", "Prefers a small, collaborative, high-trust team", "Reluctant to discipline or confront — relies on vision to pull people", "Can struggle with hard operational choices that hurt individuals"],
    asTeammate: ["The person who writes the sentence that captures what the team actually stands for", "Notices the overlooked teammate and makes sure they are heard", "Prefers one-to-one conversations over large meetings"],
    cautionCareers: ["High-pressure sales or aggressive negotiation roles", "Highly bureaucratic, values-empty corporate environments"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "Your twenties are a decade of exploration. Test your values in the real world and notice which survive contact with reality. Build enough structure — money, habits, deadlines — that your inner life is not derailed by practical chaos." },
    { phase: "In Your 30s", description: "Now the task is translating your inner life into durable external form. Write the book, start the practice, build the craft. Learn to tolerate the imperfection of finished work — a published 80% beats a perfect 95% still sitting on your hard drive." },
    { phase: "Midlife", description: "Your inferior Thinking function starts to surface. You may become newly interested in structure, strategy, and how systems actually work. Welcome it; it gives your values real-world leverage." },
    { phase: "Mature Expression", description: "At your best, you become the quietly wise elder whose work carries years of honest inner reflection. People come to you for perspective, and you give it without needing to be right." },
  ],
  topGrowthChallenges: ["Finish the creative project — the world needs your version of it, imperfect and shipped", "Name your feelings out loud before they turn into resentment", "Build enough structure to protect your creative life — logistics are not the enemy of art"],
  famousPeople: [
    { name: "J.R.R. Tolkien", role: "Author", reason: "Built a whole inner world and let it become the outer one" },
    { name: "Ryūnosuke Akutagawa", role: "Writer", reason: "Inward, idealistic author who explored conscience, morality, and the inner world" },
    { name: "William Shakespeare", role: "Playwright", reason: "Captured the full range of human feeling in language" },
    { name: "Princess Diana", role: "Humanitarian", reason: "Empathic, values-driven, reached people through quiet, authentic presence" },
    { name: "Vincent van Gogh", role: "Painter", reason: "Intense inner life poured into art that still moves people" },
    { name: "Osamu Dazai", role: "Novelist", reason: "Searingly honest about the inner self; turned private feeling into literature" },
    { name: "Audrey Hepburn", role: "Actress & humanitarian", reason: "Gentle, principled, gave later life to service" },
    { name: "Fred Rogers", role: "Television host & minister", reason: "Radical kindness as a sustained life's work" },
    { name: "Frodo Baggins", role: "Fictional (LOTR)", reason: "Reluctant but values-driven hero who endures for the sake of others" },
  ],
  typeComparisons: [
    {
      vsType: "INFJ",
      sharedTraits: ["Both introverted, intuitive, values-driven", "Deep inner life", "Quiet, thoughtful presence"],
      keyDifferences: ["INFPs lead with Fi (private values); INFJs lead with Ni (long-range vision)", "INFPs stay open and exploratory; INFJs drive toward a vision with closure", "INFPs feel their way; INFJs see their way"],
      youMightBeThis: "If you feel pulled toward a specific long-term future and want to organise people around it",
    },
    {
      vsType: "ENFP",
      sharedTraits: ["Both Fi-and-Ne types", "Values-driven, imaginative, authentic", "Deeply caring"],
      keyDifferences: ["INFPs recharge through solitude and process inward; ENFPs recharge through people and process outward", "INFPs are quietly selective; ENFPs are expansively warm", "INFPs write; ENFPs talk"],
      youMightBeThis: "If you come alive around people and feel drained by long stretches alone",
    },
  ],
  affirmations: ["My inner life is real and worth sharing — my voice belongs in the world.", "I can honour my values and still build the structure that lets them live.", "Speaking my truth early is kinder than resenting it later."],
};
