import type { PremiumTypeData } from '../premiumTypeData';

export const INTJ: PremiumTypeData = {
  code: "INTJ",
  name: "The Strategist",
  tagline: "Designing complex systems that others cannot see yet",
  accentColor: "hsl(265 60% 50%)",
  traits: ["Introverted", "Intuitive", "Thinking", "Judging"],
  famousQuote: { text: "Vision without execution is hallucination.", person: "Often attributed to leaders of the INTJ mold" },
  introduction: [
    "INTJs are analytical problem-solvers who approach life as a long chess game. They identify patterns early, see where events are heading, and work steadily toward a future only they have fully mapped out. They value insight, competence, and the independence to pursue their own conclusions.",
    "INTJs take an objective approach to problems and are comfortable reasoning from first principles. They have little patience for unexamined tradition, wishful thinking, or emotional arguments that ignore the data. They tend to be strategic, analytical, reserved, and quietly determined.",
    "INTJs focus on the future — what could be, what is not yet — rather than what is merely present. They use proven logic and hard-won experience, but the real engine is an inner picture of the system they are building. They are likely to be conceptual, long-range, independent, and highly self-directed.",
    "INTJs are usually excellent planners because they think in systems and second-order consequences. They anticipate obstacles, redesign processes rather than accept them, and pursue a single high-quality plan rather than a dozen half-formed ones. They prefer to do fewer things, better, and on their own terms.",
    "Because INTJs think several steps ahead, others rely on them for judgement on complex problems — but may also find them hard to read. They do not explain their reasoning unprompted, and can come across as private or aloof. When they speak, it is usually because the idea is already fully formed.",
    "Others see INTJs as composed, strategic, independent, and sometimes intimidating. Inside a small, trusted circle, they are warm, loyal, and surprisingly playful. They take their commitments seriously and quietly show up for the few people and projects they truly care about.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Introverted Intuition", abbr: "Ni", description: "Your primary mode. You perceive patterns and deeper meanings below the surface of events, often grasping where a situation is heading long before others. This inner sight is the engine of your long-range strategy." },
    auxiliary: { name: "Extraverted Thinking", abbr: "Te", description: "Your support system. You translate your inner vision into objective, structured action — prioritising tasks logically, setting standards, and driving plans to completion in the outer world." },
    tertiary: { name: "Introverted Feeling", abbr: "Fi", description: "Developing with age. A private but strong inner value system guides what is worth your time. As it matures you become more willing to reveal what personally matters to you, not just what is most effective." },
    inferior: { name: "Extraverted Sensing", abbr: "Se", description: "Your hidden edge and stress trigger. You can neglect the body, the present moment, and sensory enjoyment. Under heavy stress, you may lurch into impulsive sensation-seeking or fixate on worst-case physical details." },
  },
  strengths: [
    { title: "Strategic Vision", description: "INTJs see where things are heading years before others do. They naturally frame today's decisions against a long-term trajectory and refuse to optimise for the short term alone." },
    { title: "Independent Thinking", description: "Free of the need to conform, INTJs pursue ideas on their merits. They are rarely swayed by social pressure and will hold an unpopular position when the reasoning supports it." },
    { title: "Rigorous Analysis", description: "They examine assumptions relentlessly. Faulty reasoning, sloppy logic, and motivated thinking do not survive long once an INTJ has them in view." },
    { title: "High Standards of Competence", description: "INTJs demand excellence from themselves first. Their bar for quality and their refusal to ship half-finished work pulls the whole team upward." },
    { title: "Decisive When It Counts", description: "Once they have analysed a situation they commit. They do not waver, do not chase consensus, and rarely second-guess a well-formed plan." },
    { title: "Self-Reliance", description: "They can research, build, and execute alone for long stretches — a rare capacity in a world that depends on constant coordination and validation." },
  ],
  weaknesses: [
    { title: "Emotionally Distant", description: "INTJs process feelings internally and can appear cold or dismissive even when they care deeply. Their inner world rarely makes it out in words." },
    { title: "Overly Critical", description: "Their drive for improvement can tip into harsh judgement — of themselves, their work, and the people around them. The same standards that power their excellence can alienate their team." },
    { title: "Impatient with Inefficiency", description: "They have little tolerance for repetition, small talk, or people they perceive as moving too slowly. This impatience often leaks out nonverbally." },
    { title: "Dismissive of Emotional Input", description: "INTJs may discount feelings-based arguments as illogical, missing information that actually matters to the decision and the people affected by it." },
    { title: "Stubbornly Private", description: "Their reluctance to share reasoning or inner experience can leave teammates and partners feeling shut out, uncertain, and unable to help." },
  ],
  stressTriggers: [
    "Having carefully formed plans disrupted or overturned at the last minute",
    "Being forced into constant small talk or shallow social performance",
    "Working with people who reject data and rely on emotion alone",
    "Being micromanaged or second-guessed inside their area of competence",
    "Having their independence, intelligence, or judgement questioned publicly",
    "Environments with no clear structure, logic, or long-term direction",
    "Being pushed to act quickly before they have thought something through",
  ],
  stressSigns: [
    "Becoming cold, withdrawn, and dismissive of everyone around them",
    "Fixating on small sensory details, physical symptoms, or worst-case outcomes",
    "Uncharacteristic bursts of sarcasm, cynicism, or cutting remarks",
    "Impulsive escape behaviours — binge-watching, overspending, overeating",
    "Catastrophising future scenarios and losing their usual calm reasoning",
    "Cutting off communication and refusing to discuss what is actually wrong",
  ],
  recoveryStrategies: [
    "Spend time alone with a complex book, puzzle, or strategic project",
    "Get outside for a long, quiet walk to reset the nervous system",
    "Talk to one trusted person who will listen without trying to problem-solve",
    "Return to a single concrete task that offers real, measurable progress",
    "Limit incoming input — close the inbox, postpone decisions, protect the mind",
  ],
  socialBattery: 25,
  relationships: {
    narrative: "INTJs approach love the way they approach everything else — thoughtfully, selectively, and with long-term intent. They are slow to commit, but once they do, they are loyal and invested for the long haul. They express love through intellectual engagement, reliability, and the quiet effort of making a partner's life run more smoothly. Verbal reassurance is not their native language; they would rather solve the problem. They need a partner who respects their autonomy, engages with them intellectually, and can read the care behind their actions even when the words are sparse.",
    offers: ["Deep, considered loyalty once they have chosen you", "An intellectual partner who takes your ideas seriously", "Calm, competent handling of life's practical demands"],
    needs: ["Space and long stretches of alone time without guilt", "Intellectual depth — conversations that go beyond the surface", "A partner who is honest, self-aware, and emotionally steady"],
    challenges: ["Can appear cold or detached when under stress", "Struggles to express affection in words in the moment", "May retreat into work or analysis rather than address conflict head-on"],
    compatibleWith: [
      { type: "ENFP", reason: "Shared intuition paired with opposite energy creates a natural balance of depth and spark" },
      { type: "ENTP", reason: "An intellectual peer who enjoys debate and abstract exploration alongside you" },
      { type: "INFJ", reason: "A rare fellow Ni-user who understands the inner life without needing it explained" },
    ],
  },
  friendships: {
    narrative: "INTJs keep a small, tightly-curated circle. They prefer one or two friends they can speak with at real depth over a large social network. They are not the friends who check in every week, but they are the friends who remember exactly what matters to you and will quietly solve your hardest problem without being asked. Quality, never quantity.",
    positives: ["The friend who gives you genuinely strategic advice when it counts", "The friend who reads the book you recommended and comes back with a real argument", "The friend who shows up steadily — even after months of silence, as if no time has passed"],
    watchOuts: ["Can be harsh or bluntly correcting when the topic is impersonal", "May go silent for weeks and expect others to understand it is not personal"],
  },
  career: {
    narrative: "INTJs thrive in roles where they can think strategically, work autonomously, and build systems that last. They do their best work when given a complex problem and left alone to solve it. They are natural designers, analysts, and long-range planners — and tend to lose motivation quickly in environments dominated by politics, shallow social demands, or constant short-term firefighting.",
    bestCareers: [
      { label: "Strategy Consultant", icon: "briefcase" },
      { label: "Architect", icon: "building" },
      { label: "Software Engineer", icon: "building" },
      { label: "Scientist / Researcher", icon: "briefcase" },
      { label: "Investment Analyst", icon: "bar-chart" },
      { label: "Engineering Director", icon: "building" },
      { label: "Systems Designer", icon: "briefcase" },
      { label: "Academic / Professor", icon: "graduation-cap" },
    ],
    leadershipStyle: ["Leads by vision — sets the long-range direction and expects teams to align", "Delegates the what and cares less about the how, so long as standards hold", "Makes decisions from data and independent judgement, not group consensus", "Tends to lead through written strategy and documents, not charismatic rallying"],
    asTeammate: ["Brings rigour and long-term perspective to every project", "Flags structural flaws early, before they become crises", "Prefers async, written communication over constant meetings"],
    cautionCareers: ["High-volume customer service (repetitive social demands drain the battery quickly)", "Fast-changing sales roles with no chance to design a considered approach"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "You prove your mind in your twenties — earning credibility through the depth and quality of your work. Focus on building just enough social and communication skill to translate your ideas. A vision matters far less if nobody can follow it." },
    { phase: "In Your 30s", description: "Your competence is established; now your challenge is integration. Learn to involve others in the plan rather than dropping finished blueprints on their desks. The best strategists in their thirties are the ones who can recruit and keep great collaborators." },
    { phase: "Midlife", description: "Your inferior Sensing function starts to open up. You may find unexpected joy in the physical world — travel, food, a craft, the body. Lean into it; it balances the pure abstraction that has defined your earlier life." },
    { phase: "Mature Expression", description: "At your best, you become the strategist people actually listen to — not because you demand it, but because your track record speaks for itself. You combine long-range clarity with hard-won warmth." },
  ],
  topGrowthChallenges: ["Practice sharing your reasoning out loud, not just your conclusion — people follow ideas they understand", "When you feel dismissive of an emotional argument, pause and ask what information you might be missing", "Protect time for rest, movement, and beauty — they are not distractions from your work, they fuel it"],
  famousPeople: [
    { name: "Elon Musk", role: "Engineer & entrepreneur", reason: "Long-horizon planning, contrarian bets, system redesign of entire industries" },
    { name: "Isaac Newton", role: "Scientist & mathematician", reason: "Relentless self-directed study, theory-building from first principles" },
    { name: "Friedrich Nietzsche", role: "Philosopher", reason: "Independent thinker, systematic critique of inherited assumptions" },
    { name: "Michelle Obama", role: "Former US First Lady", reason: "Strategic, composed, long-term focused, privately warm" },
    { name: "Nikola Tesla", role: "Inventor", reason: "Highly internal, visionary, deeply focused on long-term technological futures" },
    { name: "Stephen Hawking", role: "Physicist", reason: "Independent thinker with disciplined analytical rigour" },
    { name: "Gandalf", role: "Fictional (Lord of the Rings)", reason: "Long-sighted, strategic, operates behind the scenes toward a grand plan" },
  ],
  typeComparisons: [
    {
      vsType: "INTP",
      sharedTraits: ["Both introverted intuitives who enjoy theoretical thought", "Prefer a small, trusted circle", "Comfortable alone for long periods"],
      keyDifferences: ["INTJs close options and execute toward one chosen plan; INTPs stay open and keep exploring", "INTJs want a decision and a deadline; INTPs want more data and more debate", "INTJs drive long-range implementation; INTPs dissect the underlying model"],
      youMightBeThis: "If you find yourself more energised by open-ended theory than by finishing a plan, and resist committing to one direction",
    },
    {
      vsType: "ENTJ",
      sharedTraits: ["Both strategic, Thinking-dominant, long-range oriented", "Natural planners with high standards"],
      keyDifferences: ["INTJs run strategy privately and delegate execution; ENTJs lead execution publicly and from the front", "INTJs recharge alone; ENTJs recharge through directing and engaging with people", "INTJs build the blueprint; ENTJs rally the team to build it"],
      youMightBeThis: "If you come alive leading people in real time rather than plotting the plan in solitude",
    },
  ],
  affirmations: ["My depth of thought is a gift — I give the world my best ideas, not my hurried reactions.", "I can let people in without losing my independence or my focus.", "My vision becomes more powerful when I share the reasoning behind it, not just the conclusion."],
};
