import type { PremiumTypeData } from '../premiumTypeData';

export const INTP: PremiumTypeData = {
  code: "INTP",
  name: "The Thinker",
  tagline: "Solving a theoretical problem that has stumped everyone else",
  accentColor: "hsl(255 55% 55%)",
  traits: ["Introverted", "Intuitive", "Thinking", "Perceiving"],
  famousQuote: { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", person: "Often attributed to thinkers of the INTP mold" },
  introduction: [
    "INTPs are the logicians of the type world — curious, theoretical, and most alive when a hard problem lands in their lap. They are driven by the pleasure of understanding for its own sake, and will often pursue a question long after its practical usefulness has worn off.",
    "INTPs take a deeply analytical approach to problems and are comfortable living in the abstract. They pull ideas apart, test internal consistency, and rebuild them cleanly. They can be skeptical, precise, and quietly contrarian — especially when someone asserts something they cannot justify.",
    "INTPs focus on the possible rather than the immediate. They use frameworks, models, and analogies more than experience or tradition. They tend to be inventive, open-minded, intellectually flexible, and resistant to premature conclusions.",
    "INTPs are usually excellent at seeing flaws in a system — logical gaps, hidden contradictions, unexamined assumptions. They are less drawn to execution and hierarchy, and may leave loose ends when the intellectual work is done and the administrative work remains.",
    "Because INTPs keep their conclusions provisional, others sometimes mistake them for indecisive or detached. In reality they are simply unwilling to commit until the reasoning is sound. Given time and space, their thinking is often sharper than anyone else's in the room.",
    "Others see INTPs as quiet, thoughtful, a bit absent-minded, and suddenly brilliant. Inside their small circle, they are warm, funny, and full of odd, delightful ideas. They take real relationships seriously, but need a great deal of solitude to stay themselves.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Introverted Thinking", abbr: "Ti", description: "Your primary mode. You build precise internal frameworks for how things work, and hold each belief to a standard of internal consistency. Understanding the underlying logic is what makes the world feel ordered." },
    auxiliary: { name: "Extraverted Intuition", abbr: "Ne", description: "Your support system. You generate a constant stream of possibilities, alternatives, and connections between unrelated fields. This is how your private logic meets the wider world of ideas." },
    tertiary: { name: "Introverted Sensing", abbr: "Si", description: "Developing with age. Over time you lean more on remembered detail, past precedent, and personal routine. It quietly anchors your abstract mind in lived experience." },
    inferior: { name: "Extraverted Feeling", abbr: "Fe", description: "Your hidden edge and stress trigger. Group harmony, social expectations, and other people's feelings can feel like a foreign language. Under stress you may become awkwardly emotional, hypersensitive, or fixated on being liked." },
  },
  strengths: [
    { title: "Original Thinking", description: "INTPs see problems from angles nobody else considers. They question the obvious and frequently find an answer that was hiding in plain sight." },
    { title: "Intellectual Honesty", description: "They care more about being right than about looking right. They will happily change position when the evidence shifts — an unusually rare quality." },
    { title: "Analytical Depth", description: "INTPs take a system apart layer by layer until they understand it. Their analyses tend to hold up under pressure because nothing was skipped." },
    { title: "Open-Minded Curiosity", description: "Few topics bore them. They can go from chess to biology to metaphysics in a single afternoon and bring real insight to each." },
    { title: "Independent and Self-Reliant", description: "They are comfortable alone for long stretches and can pursue difficult projects without external structure or reassurance." },
    { title: "Creative Problem Solving", description: "Because they do not default to standard answers, INTPs often produce elegant, unexpected solutions that more conventional thinkers overlook." },
  ],
  weaknesses: [
    { title: "Struggles with Follow-Through", description: "INTPs often lose interest once the intellectual puzzle is solved. Execution, paperwork, and final polish can suffer badly." },
    { title: "Emotionally Guarded", description: "They tend to underrate and underexpress their own feelings, which can leave partners and teammates feeling disconnected." },
    { title: "Prone to Overthinking", description: "Their strength in analysis becomes a trap when small decisions are dissected endlessly. They can paralyze themselves in pursuit of the optimal answer." },
    { title: "Socially Inattentive", description: "Small talk, group rituals, and relational maintenance drain them. They may ignore social cues they consider trivial and hurt people unintentionally." },
    { title: "Dismissive of Tradition", description: "If a rule cannot justify itself logically, an INTP may discard it — sometimes missing its real value in coordination, comfort, or shared meaning." },
  ],
  stressTriggers: [
    "Being forced into fast decisions without time to think them through",
    "Dealing with emotional conflict, drama, or heavy interpersonal demands",
    "Repetitive, procedural work with no opportunity for analysis",
    "Having their logic or competence questioned by someone less rigorous",
    "Tight, constantly-moving deadlines that prevent deep focus",
    "Loud, chaotic, or emotionally charged environments",
    "Being expected to perform socially — networking, small talk, politics",
  ],
  stressSigns: [
    "Withdrawing entirely and going silent for days at a time",
    "Obsessive over-analysis that spirals and produces no decision",
    "Uncharacteristic emotional outbursts that feel like they came from nowhere",
    "Becoming cynical, sarcastic, or dismissive of everything and everyone",
    "Neglecting food, sleep, and basic routines while lost in a problem",
    "Sudden, desperate attempts to please others or seek approval",
  ],
  recoveryStrategies: [
    "Take a long solo walk to let the mind process without an audience",
    "Retreat into a purely mental hobby — a puzzle, a book, a game",
    "Talk with one calm, logical friend who will reason with you, not coddle you",
    "Limit incoming input — close social apps, silence notifications, protect the quiet",
    "Return to the basics: water, food, sleep, a familiar routine",
  ],
  socialBattery: 20,
  relationships: {
    narrative: "INTPs approach love with curiosity and caution. They are slow to open up but deeply loyal once they do. They show affection through shared ideas, quiet presence, and small thoughtful acts rather than declarations. They can struggle with the emotional maintenance side of a relationship — remembering anniversaries, expressing feelings spontaneously, handling conflict in real time — and often do better with a patient partner who can read the care behind the awkward delivery. They want someone who respects their solitude and enjoys long, wandering conversations.",
    offers: ["A deeply original mind that will never bore you", "Quiet, unflashy loyalty and real intellectual respect", "A partner who lets you be fully yourself, oddities and all"],
    needs: ["Generous amounts of alone time without explanation", "Intellectual conversation and shared curiosity", "A partner who is not triggered by bluntness or long silences"],
    challenges: ["Difficulty expressing emotion and handling heavy feelings", "Can withdraw or overanalyse during conflict rather than engage", "May forget the small rituals of relationship maintenance"],
    compatibleWith: [
      { type: "ENTJ", reason: "A decisive partner who takes your ideas and actually executes them in the world" },
      { type: "ENFJ", reason: "Warm, structured energy that complements your internal abstraction" },
      { type: "INFJ", reason: "A fellow introspective type who understands long silences and deep conversation" },
    ],
  },
  friendships: {
    narrative: "INTPs are loyal, low-maintenance friends who often go quiet for long stretches and then pick up exactly where they left off. They do not need constant contact; they need depth, honesty, and the freedom to be themselves. The friends who stick around learn that an INTP's silence is not distance — it is processing.",
    positives: ["The friend who sends you the weird article at 2am because it made them think of you", "The friend who will actually debate an idea with you rather than nod politely", "The friend who keeps no grudge and is happy to resume after a year apart"],
    watchOuts: ["Can disappear for long stretches and forget to reach out first", "May pick holes in your reasoning before noticing you are upset"],
  },
  career: {
    narrative: "INTPs thrive where autonomy and intellectual challenge meet. They want hard problems, intelligent colleagues, and the freedom to pursue the question the way they want to pursue it. They struggle in hierarchies that value loyalty over logic and in roles dominated by repetitive procedure or relentless interpersonal performance.",
    bestCareers: [
      { label: "Research Scientist", icon: "briefcase" },
      { label: "Software Engineer", icon: "building" },
      { label: "Mathematician", icon: "briefcase" },
      { label: "Philosopher", icon: "briefcase" },
      { label: "Data Scientist", icon: "briefcase" },
      { label: "Systems Architect", icon: "building" },
      { label: "University Professor", icon: "graduation-cap" },
      { label: "Writer / Analyst", icon: "bar-chart" },
    ],
    leadershipStyle: ["Leads through ideas and expertise rather than authority", "Prefers flat teams of capable specialists over traditional hierarchy", "Trusts people to self-direct and expects them to think for themselves", "Can neglect administrative leadership — feedback, recognition, ceremony"],
    asTeammate: ["The person who finds the flaw in the plan nobody else spotted", "Brings unexpected frameworks and analogies from other domains", "Prefers written async discussion over constant synchronous meetings"],
    cautionCareers: ["High-pressure sales or quota-driven customer-facing roles", "Rigid bureaucratic environments where process outranks thinking"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "Your twenties are the decade of deep learning. Let yourself go wide and weird — follow the odd interests, stack up frameworks, and resist the pressure to narrow down too early. But practice finishing a few things all the way through; completion is where depth becomes value." },
    { phase: "In Your 30s", description: "You know how to think; now learn to ship. Build rituals around deadlines, collaborators, and public commitments so that your ideas actually reach the world. This is also the decade to stop treating emotions as someone else's problem." },
    { phase: "Midlife", description: "Your inferior Feeling function begins to surface. You may become unexpectedly moved by relationships, community, and your effect on other people. Treat this growth as a skill to develop, not an interruption of your real work." },
    { phase: "Mature Expression", description: "At your best, you become the wise, slightly eccentric thinker whose insights are trusted because they have been tested against decades of honest reflection. Warmth is added to rigour without replacing it." },
  ],
  topGrowthChallenges: ["Finish more than you start — every completed project teaches more than three abandoned ones", "Practice naming your feelings out loud, even when it feels unnecessary; the people who love you need the translation", "Commit to one path long enough to master it before the next shiny question arrives"],
  famousPeople: [
    { name: "Albert Einstein", role: "Theoretical physicist", reason: "Reframed physics from first principles, comfortable with deep abstraction and long solitude" },
    { name: "Hideki Yukawa", role: "Theoretical physicist", reason: "Independent thinker who derived a foundational theory from pure conceptual reasoning" },
    { name: "Charles Darwin", role: "Naturalist", reason: "Patient, theoretical, pieced together a framework that reshaped biology" },
    { name: "Marie Curie", role: "Physicist & chemist", reason: "Intense, self-directed investigator, pursued the problem rather than the recognition" },
    { name: "Bill Gates", role: "Technologist", reason: "Early INTP tinkerer before becoming a public figure; loves systems and deep reading" },
    { name: "Mori Ōgai", role: "Writer & army surgeon", reason: "Polymath who pursued ideas across literature, medicine, and philosophy with cool analysis" },
    { name: "René Descartes", role: "Philosopher", reason: "Reasoned from the ground up, questioned everything, built from axioms" },
    { name: "Abraham Lincoln", role: "US President", reason: "Thoughtful, analytical, famously patient in reasoning and decision-making" },
    { name: "Gregory House", role: "Fictional (House M.D.)", reason: "Brilliant, logical, socially prickly, driven by the puzzle more than the praise" },
  ],
  typeComparisons: [
    {
      vsType: "INTJ",
      sharedTraits: ["Both introverted intuitives", "Love theory and abstract reasoning", "Prefer depth over breadth in relationships"],
      keyDifferences: ["INTPs stay open and keep exploring; INTJs pick a path and execute", "INTPs chase the elegant model; INTJs chase the finished system", "INTPs tolerate ambiguity; INTJs want closure and a deadline"],
      youMightBeThis: "If you find yourself pushing for a clear plan and a due date, and losing patience with endless 'what ifs'",
    },
    {
      vsType: "ISTP",
      sharedTraits: ["Both Ti-dominant with a pragmatic, analytical streak", "Independent and low-drama", "Great at taking systems apart"],
      keyDifferences: ["INTPs reason about ideas and theory; ISTPs reason about physical, mechanical systems", "INTPs enjoy the abstract model; ISTPs enjoy hands-on problem-solving", "INTPs write; ISTPs build"],
      youMightBeThis: "If your instinct is always to pick up the tool and try it, not to write down the theory first",
    },
  ],
  affirmations: ["My mind is most valuable when I let it finish what it starts.", "I can share my feelings and my reasoning — the people I love deserve both.", "Commitment and curiosity are not enemies; one lets the other reach the world."],
};
