import type { PremiumTypeData } from '../premiumTypeData';

export const ISFJ: PremiumTypeData = {
  code: "ISFJ",
  name: "The Protector",
  tagline: "Providing steady, unwavering support to someone in need",
  accentColor: "hsl(210 50% 55%)",
  traits: ["Introverted", "Observant", "Feeling", "Judging"],
  famousQuote: { text: "No act of kindness, no matter how small, is ever wasted.", person: "Often attributed to protectors of the ISFJ mold" },
  introduction: [
    "ISFJs are the quiet guardians of the type world. They are the people who remember the birthdays, bring the casserole, fix the small thing nobody else noticed, and hold families, teams, and communities together without ever asking for credit.",
    "ISFJs approach life with care, patience, and a deep sense of responsibility for the people around them. Beneath the gentle exterior is an iron sense of duty — once they have committed to a person or an institution, they rarely withdraw that loyalty.",
    "ISFJs focus on the present and on lived experience. They trust what has worked and are attentive to the details of daily life — faces, routines, the small cues that tell them how people around them are actually doing. They tend to be loyal, observant, warm, and conscientious.",
    "ISFJs are usually excellent caregivers, administrators, teachers, nurses, and quiet organisers of community. They bring a rare combination of practical competence and emotional attunement, and they are at their best when they can care for specific people over time.",
    "Because ISFJs give so much and ask so little, they can be quietly taken advantage of. They find it hard to say no, and can overgive until they are hollow. Learning to protect their own energy without losing their generosity is their great life task.",
    "Others see ISFJs as kind, dependable, modest, and sometimes hard to read beyond the helpfulness. Inside their small circle they are warm, funny, deeply loyal, and carry a long memory for both love and hurt. They are slow to trust and very slow to leave.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Introverted Sensing", abbr: "Si", description: "Your primary mode. You hold a detailed inner library of how things have been — routines, people, traditions, sensory memory. It is how you track the life around you with such loving precision." },
    auxiliary: { name: "Extraverted Feeling", abbr: "Fe", description: "Your support system. You tune in to the emotional state of the group and work quietly to keep it well. This is how your private attention becomes visible care." },
    tertiary: { name: "Introverted Thinking", abbr: "Ti", description: "Developing with age. Over time you build more analytical clarity and inner logical precision. It makes your care both kinder and sharper." },
    inferior: { name: "Extraverted Intuition", abbr: "Ne", description: "Your hidden edge and stress trigger. Wild change and abstract speculation are not home. Under heavy stress you may catastrophise, worry about unlikely disasters, or lose faith in people and plans you have trusted for years." },
  },
  strengths: [
    { title: "Deep Loyalty", description: "Once an ISFJ has chosen you, they are with you for life. Their commitment is quiet, constant, and rare." },
    { title: "Practical Caregiving", description: "They translate love into tangible help — meals, calls, rides, rearranged schedules. Their care is never just words." },
    { title: "Attention to Detail", description: "They notice what others miss: the small sign a friend is struggling, the procedural flaw, the forgotten birthday." },
    { title: "Humility and Service", description: "They do not need credit. They will keep going long after the applauding types have moved on." },
    { title: "Dependable Follow-Through", description: "They finish what they start and keep the promises they make. Whole communities quietly rely on this." },
    { title: "Protective of Their People", description: "Under the softness is a surprisingly firm defender when someone they love is threatened." },
  ],
  weaknesses: [
    { title: "Difficulty Saying No", description: "They over-give. Responsibilities accumulate that were never theirs to carry, and no one notices until the ISFJ burns out." },
    { title: "Resists Change", description: "They find comfort in the familiar and can cling to a past that no longer serves them." },
    { title: "Internalises Criticism", description: "Even mild feedback can sting deeply and live inside them for a long time." },
    { title: "Undersells Themselves", description: "They give others credit and stay in the background. They can end up under-rewarded and quietly resentful." },
    { title: "Avoids Conflict", description: "They will swallow grievances to keep the peace, even as unaddressed issues corrode the relationship underneath." },
  ],
  stressTriggers: [
    "Being taken for granted by the very people they care for",
    "Conflict inside a close family, team, or community",
    "Constant change to routines, homes, or institutions they love",
    "Being rushed into decisions they have not had time to think through",
    "Feeling unseen, unappreciated, or publicly criticised",
    "Having their core values dismissed or mocked",
    "Watching someone they love make a destructive choice",
  ],
  stressSigns: [
    "Becoming quiet, withdrawn, and emotionally distant",
    "Physical symptoms — headaches, insomnia, stress illness",
    "Uncharacteristic pessimism and worst-case thinking",
    "Martyrdom — continuing to give while quietly resenting everyone",
    "Sudden loss of faith in people they normally trust",
    "Irritability toward the people they usually nurture",
  ],
  recoveryStrategies: [
    "A full, guilt-free block of alone time away from all demands",
    "Return to a comforting routine — familiar food, music, places",
    "One honest conversation with someone who takes care of them for once",
    "Gentle physical activity — walking, gardening, swimming",
    "Write down what they actually feel, not what everyone else needs",
  ],
  socialBattery: 30,
  relationships: {
    narrative: "ISFJs love through loyalty, tenderness, and sustained practical care. They commit slowly but for life, and they remember every small detail about their partner. They show love through acts of service, home-making, and unwavering presence. Their challenge is that they give so much they can forget to ask for anything back, then quietly resent it. They need a partner who notices their needs, initiates care for them, and invites them to speak their own feelings out loud.",
    offers: ["Deep, abiding loyalty and everyday tenderness", "A partner who remembers the small details and makes home feel like home", "Calm, steady presence through every hard season"],
    needs: ["A partner who actively notices and cares for them in return", "Patience with their slower, more internal emotional processing", "A safe space to voice their own needs without guilt"],
    challenges: ["Tend to over-give and then feel unseen", "May avoid difficult conversations until resentment has built", "Can idealise traditional roles and resent modern flexibility"],
    compatibleWith: [
      { type: "ESTP", reason: "A lively partner who pulls the ISFJ out of duty and into play" },
      { type: "ESFP", reason: "A warm, expressive counterpart who receives their care with real appreciation" },
      { type: "ISTJ", reason: "A fellow Si-dominant who understands quiet devotion and long commitment" },
    ],
  },
  friendships: {
    narrative: "ISFJs are lifelong friends. They keep the same small circle for decades, remember every detail of each friend's life, and show up through every crisis. Their friendship is quiet, loyal, and extraordinarily steady — the kind of friendship that becomes more valuable the longer it lasts.",
    positives: ["The friend who remembers your hospital appointment and calls to check after", "The friend who cooks for you during the hard week without being asked", "The friend who has kept every card and photo and quietly treasures the history"],
    watchOuts: ["May over-give and quietly burn out on friends who do not reciprocate", "Can withdraw silently when hurt rather than name it"],
  },
  career: {
    narrative: "ISFJs thrive in caring, structured, service-oriented roles where attention to detail, reliability, and genuine care for specific people are all rewarded. They excel in nursing, teaching, administration, social work, and support functions that make an organisation humanly liveable. They struggle in cutthroat, purely transactional environments that treat people as interchangeable.",
    bestCareers: [
      { label: "Nurse / Paediatric Nurse", icon: "briefcase" },
      { label: "Teacher (especially early years)", icon: "graduation-cap" },
      { label: "Social Worker", icon: "briefcase" },
      { label: "HR / People Partner", icon: "briefcase" },
      { label: "Office Manager", icon: "briefcase" },
      { label: "Librarian", icon: "briefcase" },
      { label: "Administrative Director", icon: "briefcase" },
      { label: "Family Doctor", icon: "briefcase" },
    ],
    leadershipStyle: ["Leads by quiet example, consistent care, and attention to people as individuals", "Prefers small, stable, trusting teams", "Holds firm standards gently — rarely raises voice, rarely wavers", "Can struggle to deliver harsh feedback or make people-hurting decisions"],
    asTeammate: ["The person who keeps the team humanly healthy under pressure", "Notices who is struggling quietly and checks in one-to-one", "Catches errors others miss and never makes a show of the catch"],
    cautionCareers: ["High-pressure sales or cutthroat negotiation roles", "Fast-moving startups with constant pivots and unstable routines"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "Your twenties are the decade of showing up reliably while learning a crucial skill: saying no. Begin building the boundary muscle early. You will need it every decade from here, and people will only take as much as you allow." },
    { phase: "In Your 30s", description: "Now the task is claiming your own life alongside the lives you serve. Ask for what you need out loud. Invest in your own growth and goals as seriously as you invest in others. A fully alive ISFJ is a gift to everyone they touch." },
    { phase: "Midlife", description: "Your inferior Intuition function begins to surface. You may develop unexpected interest in new ideas, places, and possibilities you have never considered. Welcome it; it keeps your loyalty from turning into a cage." },
    { phase: "Mature Expression", description: "At your best, you become the beloved elder whose long life of care has shaped the people around you. Your quiet influence is now widely acknowledged, and you finally let yourself receive it." },
  ],
  topGrowthChallenges: ["Practice saying a clear no — your yes becomes more valuable when it is chosen freely", "Name your own needs out loud; the people who love you cannot read your mind", "Invest in your own growth, not just the growth of everyone around you"],
  famousPeople: [
    { name: "Mother Teresa", role: "Humanitarian", reason: "Lifelong quiet service; relentless practical care for the poor" },
    { name: "Rosa Parks", role: "Civil rights pioneer", reason: "Quiet, principled, immovable on what she knew to be right" },
    { name: "Queen Elizabeth II", role: "Monarch", reason: "Seven decades of patient, dutiful service to her role" },
    { name: "Jimmy Stewart", role: "Actor", reason: "Warm, earnest, dependable; embodied everyday decency on screen" },
    { name: "Kate Middleton", role: "Princess of Wales", reason: "Composed, service-oriented, attentive to tradition and family" },
    { name: "Samwise Gamgee", role: "Fictional (Lord of the Rings)", reason: "Steadfast friend, quietly carried the weight of the journey" },
    { name: "Beth March", role: "Fictional (Little Women)", reason: "Gentle, caring, devoted to family and quiet service" },
  ],
  typeComparisons: [
    {
      vsType: "ESFJ",
      sharedTraits: ["Both Fe-plus-Si types", "Warm, service-oriented, tradition-honouring", "Remember details about people"],
      keyDifferences: ["ISFJs work quietly behind the scenes; ESFJs are more openly expressive and social", "ISFJs recharge alone; ESFJs recharge through people", "ISFJs serve one-to-one; ESFJs organise the whole group"],
      youMightBeThis: "If you thrive when you are openly hosting, organising, and social — and feel drained by extensive solitude",
    },
    {
      vsType: "ISTJ",
      sharedTraits: ["Both Si-dominant introverts", "Practical, reliable, service-oriented", "Attentive to detail"],
      keyDifferences: ["ISFJs lead with people-care (Fe); ISTJs lead with logical efficiency (Te)", "ISFJs prioritise harmony; ISTJs prioritise correctness", "ISFJs soften; ISTJs structure"],
      youMightBeThis: "If your default is to apply logic and efficiency rather than to maintain emotional harmony",
    },
  ],
  affirmations: ["My care matters — and I can give it without losing myself.", "Saying no is part of how I keep saying yes well.", "My own needs deserve the same attention I give to everyone else's."],
};
