import type { PremiumTypeData } from '../premiumTypeData';

export const ISFP: PremiumTypeData = {
  code: "ISFP",
  name: "The Artist",
  tagline: "Creating something beautiful that perfectly captures a fleeting feeling",
  accentColor: "hsl(310 45% 55%)",
  traits: ["Introverted", "Observant", "Feeling", "Perceiving"],
  famousQuote: { text: "Life isn't about finding yourself. Life is about creating yourself.", person: "Often attributed to artists of the ISFP mold" },
  introduction: [
    "ISFPs are the quiet, sensitive artists of the type world. They live through their senses and their inner values, and they express what they cannot easily say through music, art, design, movement, or the quiet care they offer specific people.",
    "ISFPs approach life gently but independently. They have a soft surface and a private spine of iron — they will not be pushed into a life that violates what they value. Beneath their quietness is a vivid, sensory, deeply felt inner world.",
    "ISFPs focus on the present moment. They perceive colour, texture, tone, atmosphere, and emotional undercurrent with unusual intensity. They tend to be sensitive, artistic, flexible, and unexpectedly adventurous within the lanes that matter to them.",
    "ISFPs are usually gifted in the arts, in caregiving roles, in craft, and in any work where aesthetic sensitivity meets hands-on presence. They may be late-bloomers in careers because they refuse paths that do not feel right, but their eventual work often carries unusual soul.",
    "Because ISFPs share so little of their inner life, others often underestimate the depth and the firmness underneath. They do not argue loudly, but they also do not give ground on what matters. Their quietness is not compliance.",
    "Others see ISFPs as kind, low-key, creatively gifted, and sometimes hard to read past the gentleness. Inside their small circle they are warm, funny, loyal, and full of small poetic gestures. They need substantial solitude and creative space and will quietly leave situations that trample them.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Introverted Feeling", abbr: "Fi", description: "Your primary mode. You hold a deeply private value system and evaluate every situation against it. Authenticity is not decorative for you — it is the basic rule of your life." },
    auxiliary: { name: "Extraverted Sensing", abbr: "Se", description: "Your support system. You are present to the physical world, to beauty and sensation, to the here and now. This is what gives your inner values their sensory, aesthetic, hands-on expression." },
    tertiary: { name: "Introverted Intuition", abbr: "Ni", description: "Developing with age. Over time you gain a deeper capacity for long-range meaning and pattern-seeing. It enriches your art and clarifies your choices." },
    inferior: { name: "Extraverted Thinking", abbr: "Te", description: "Your hidden edge and stress trigger. Logistics, structure, and strategic planning do not come naturally. Under heavy stress you may become uncharacteristically rigid, controlling, or cutting — a caricature of efficiency." },
  },
  strengths: [
    { title: "Aesthetic Sensitivity", description: "ISFPs see and feel what most people miss — colour, tone, atmosphere, small beauty. Their inner world is unusually rich." },
    { title: "Authenticity", description: "They do not fake feelings or values. What you get from an ISFP is what is actually there." },
    { title: "Present-Moment Awareness", description: "They are grounded in the body and the senses. They notice the moment as it is, not as theory says it should be." },
    { title: "Gentle Devotion", description: "Once an ISFP loves you, their loyalty is unshakeable — even if they rarely announce it." },
    { title: "Creative Expression", description: "Given time, they produce art, craft, or care that carries real feeling. They put into form what most people cannot." },
    { title: "Flexible and Adaptive", description: "They flow with circumstances rather than fighting them. Their calm can steady a chaotic environment." },
  ],
  weaknesses: [
    { title: "Struggles With Structure", description: "Long-term planning, admin, and external deadlines drain them. They can miss opportunities they actually wanted." },
    { title: "Over-Absorbs Others' Emotions", description: "Without boundaries they take on the feelings of those around them and pay for it privately." },
    { title: "Conflict-Averse", description: "They avoid direct confrontation and can let resentments build in silence." },
    { title: "Self-Doubting About Their Work", description: "They undershare their art and gifts and may hide both until long after they were ready." },
    { title: "Drift Without Direction", description: "Without a strong values anchor in their current path, they can float between roles and miss building compound strength." },
  ],
  stressTriggers: [
    "Harsh criticism, especially of their character or sincerity",
    "Highly competitive, cutthroat environments",
    "Being pushed to perform emotions they do not feel",
    "Loss of creative or private time for extended stretches",
    "Being in environments that violate their values",
    "Loud, chaotic, overly-crowded spaces",
    "Pressure to commit before they have felt into a decision",
  ],
  stressSigns: [
    "Withdrawing into silence and creating distance",
    "Uncharacteristic rigidity, harshness, or cutting remarks",
    "Physical symptoms and sleep disruption",
    "Obsessing over logistics and control they usually ignore",
    "Avoiding their own creative work — the surest sign something is wrong",
    "Cynicism about people and possibilities, which is not their default",
  ],
  recoveryStrategies: [
    "Real solitude in a beautiful environment — nature, a studio, water",
    "Creative expression with no audience or deadline",
    "Gentle physical activity — walking, swimming, dancing, yoga",
    "One honest conversation with a safe, non-judgemental person",
    "Simplify the schedule — fewer obligations, more quiet",
  ],
  socialBattery: 20,
  relationships: {
    narrative: "ISFPs love deeply, privately, and through small beautiful gestures. They commit slowly but fully and are rarely casual about intimacy. They express love through presence, shared sensory experience, and the small artful touches they put into a shared life. Their challenge is that they rarely ask openly for what they need and may withdraw when they feel unseen. They need a partner who takes their gentleness seriously, respects their creative life, and draws them out with patient care.",
    offers: ["Quiet, devoted love expressed in small beautiful ways", "A partner who sees and honours your sensory and emotional world", "Loyalty that endures across many seasons without needing announcement"],
    needs: ["A partner who respects their values and creative life", "Patience with slow, internal emotional processing", "No loud pressure — gentle invitation rather than demand"],
    challenges: ["May withdraw silently rather than raise a problem", "Can idealise a partner and struggle when reality complicates the picture", "Tend to over-accommodate and then quietly resent it"],
    compatibleWith: [
      { type: "ESTJ", reason: "A decisive, reliable partner who handles the logistics while honouring the ISFP's inner life" },
      { type: "ENFJ", reason: "A warm, structured counterpart who draws out the ISFP with patient care" },
      { type: "ESFP", reason: "A fellow Se-plus-Fi type who shares the ISFP's sensory, values-driven aliveness" },
    ],
  },
  friendships: {
    narrative: "ISFPs are quietly devoted friends who show up through small gestures that accumulate into something remarkable. They may not announce their care or text every day, but they are present across years in ways that few friendships manage. Their friendship is gentle, aesthetic, and unexpectedly deep.",
    positives: ["The friend who notices the small thing about you no one else has noticed", "The friend who brings the perfect unexpected gift at the exact right time", "The friend whose quiet company is somehow better than anyone else's conversation"],
    watchOuts: ["Can disappear for long stretches when overwhelmed", "May avoid raising friction until it has become a bigger problem"],
  },
  career: {
    narrative: "ISFPs thrive in creative, values-aligned, hands-on, beauty-oriented work. They excel in the arts, design, care work, craft, and any role where their aesthetic sensitivity and authentic presence are the actual product. They struggle in high-pressure corporate environments, cutthroat competition, or roles that require sustained performative extroversion.",
    bestCareers: [
      { label: "Artist / Designer", icon: "briefcase" },
      { label: "Musician / Composer", icon: "briefcase" },
      { label: "Photographer", icon: "briefcase" },
      { label: "Chef", icon: "briefcase" },
      { label: "Physical Therapist", icon: "briefcase" },
      { label: "Veterinary Technician", icon: "briefcase" },
      { label: "Craftsperson", icon: "briefcase" },
      { label: "Florist / Stylist", icon: "briefcase" },
    ],
    leadershipStyle: ["Leads gently, through example and quiet standards", "Prefers small, close-knit, creatively engaged teams", "Builds loyalty through personal attention rather than authority", "Can struggle with hard operational or disciplinary decisions"],
    asTeammate: ["The person whose taste lifts the quality of everything the team produces", "Notices the quiet teammate and includes them", "Prefers real conversation to performative team-building"],
    cautionCareers: ["High-pressure sales or cutthroat negotiation roles", "Large bureaucracies dominated by politics and rigid hierarchy"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "Your twenties are the decade of discovering what you actually care about — and letting that discovery shape how you spend your time. Build enough structure and income that your creative life is protected. Take your talent seriously enough to practice it consistently." },
    { phase: "In Your 30s", description: "Your craft is real now; the challenge is making it visible. Share your work, ship it, let it be imperfect and out there. Practice asking for what you need in relationships before silent resentment builds." },
    { phase: "Midlife", description: "Your inferior Thinking function begins to surface. You may develop unexpected interest in systems, strategy, and how things actually work behind the scenes. Welcome it; it gives your art leverage in the world." },
    { phase: "Mature Expression", description: "At your best, you become the quietly admired elder whose life is a long work of art — beautiful, values-led, and much deeper than the surface suggested. Your gifts finally reach the audience they deserve." },
  ],
  topGrowthChallenges: ["Ship the creative work — the world needs your version, imperfect and real", "Ask for what you need out loud before resentment arrives", "Build enough structure to protect your creative life — logistics are not the enemy of art"],
  famousPeople: [
    { name: "Frida Kahlo", role: "Painter", reason: "Turned intense inner feeling and physical experience into art that still reverberates" },
    { name: "Jun'ichirō Tanizaki", role: "Novelist", reason: "Sensual, aesthetically attuned writer devoted to beauty, mood, and quiet observation" },
    { name: "Bob Dylan", role: "Musician", reason: "Quiet, enigmatic, deeply private; expressed a generation's inner life through song" },
    { name: "Audrey Hepburn", role: "Actress & humanitarian", reason: "Gentle, elegant, values-driven, later life devoted to service" },
    { name: "Michael Jackson", role: "Musician", reason: "Physical genius, aesthetic sensitivity, profoundly private inner world" },
    { name: "Utagawa Hiroshige", role: "Ukiyo-e artist", reason: "Gentle observer of landscape and seasons; let nature speak through his prints" },
    { name: "Lana Del Rey", role: "Musician", reason: "Sensory, atmospheric, values-led artistic voice" },
    { name: "Kevin Costner", role: "Actor & director", reason: "Understated screen presence, drawn to personal, values-rich stories" },
    { name: "Arwen", role: "Fictional (LOTR)", reason: "Graceful, values-driven, devoted love under a gentle surface" },
  ],
  typeComparisons: [
    {
      vsType: "INFP",
      sharedTraits: ["Both Fi-dominant", "Values-driven, imaginative, introspective", "Deeply caring"],
      keyDifferences: ["ISFPs live through the senses and the present (Se); INFPs live through ideas and possibilities (Ne)", "ISFPs create with their hands; INFPs create with their imagination", "ISFPs show; INFPs write"],
      youMightBeThis: "If your inner life runs on ideas, metaphors, and future possibility more than on immediate sensory experience",
    },
    {
      vsType: "ESFP",
      sharedTraits: ["Both Se-plus-Fi types", "Present-focused, values-driven, sensory", "Authentic and spontaneous"],
      keyDifferences: ["ISFPs recharge alone and create privately; ESFPs recharge in public and perform openly", "ISFPs are quiet; ESFPs are expressive", "ISFPs show you through a piece; ESFPs show you in the moment"],
      youMightBeThis: "If you come alive in a room of people and feel drained by long stretches alone",
    },
  ],
  affirmations: ["My quiet art is a real gift — and the world is better for my willingness to share it.", "I can ask for what I need without losing my gentleness.", "Saying yes to structure is not a betrayal of my values; it lets them reach the world."],
};
