import type { PremiumTypeData } from '../premiumTypeData';

export const ISTJ: PremiumTypeData = {
  code: "ISTJ",
  name: "The Inspector",
  tagline: "Maintaining order and ensuring every detail is accounted for",
  accentColor: "hsl(215 45% 45%)",
  traits: ["Introverted", "Observant", "Thinking", "Judging"],
  famousQuote: { text: "Duty is ours, results are God's.", person: "Often attributed to leaders of the ISTJ mold" },
  introduction: [
    "ISTJs are the steady, trustworthy backbone of every organisation they join. They do what they say they will do — on time, to spec, and without fanfare. Their word is a contract, and their follow-through is nearly unmatched.",
    "ISTJs approach life practically and methodically. They rely on proven methods, careful record-keeping, and a deep internal library of what has worked before. They have little tolerance for sloppiness, half-measures, or self-important shortcuts.",
    "ISTJs focus on present facts and past experience. They trust what can be verified and are skeptical of untested theories. They tend to be reliable, orderly, realistic, and quietly conscientious in ways that pile up into remarkable life records.",
    "ISTJs are usually excellent administrators, engineers, auditors, and custodians of anything that must not fail. They are drawn to work where accuracy and consistency matter, and they do that work beautifully year after year.",
    "Because ISTJs are private and task-focused, others sometimes misread them as cold or rigid. In reality there is deep care under the reserve — it simply shows up as reliable action rather than verbal warmth. They love through what they do.",
    "Others see ISTJs as dependable, honest, hard-working, and sometimes hard to read. Inside their tight circle they are warm, loyal, and dryly funny. They take their commitments seriously and hold a long, quiet love for the people and institutions they give themselves to.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Introverted Sensing", abbr: "Si", description: "Your primary mode. You hold a rich internal catalogue of how things have worked before — processes, procedures, standards, details. It is the bedrock of your reliability." },
    auxiliary: { name: "Extraverted Thinking", abbr: "Te", description: "Your support system. You organise the outer world — plans, schedules, systems — using logic and measurable progress. This is how your inner memory becomes visible competence." },
    tertiary: { name: "Introverted Feeling", abbr: "Fi", description: "Developing with age. A private value system becomes more explicit over time. You begin to articulate what you personally care about, not just what is correct or required." },
    inferior: { name: "Extraverted Intuition", abbr: "Ne", description: "Your hidden edge and stress trigger. Wild possibilities, abstract speculation, and disruptive change do not come naturally. Under heavy stress you may catastrophise, obsess over unlikely disasters, or freeze." },
  },
  strengths: [
    { title: "Extreme Reliability", description: "If an ISTJ commits, it will be done — correctly, on time, and without hand-holding. They are the people organisations are built on." },
    { title: "Attention to Detail", description: "Nothing slips past a well-rested ISTJ. They catch the missing number, the broken process, the forgotten step." },
    { title: "Practical Problem-Solving", description: "They apply proven methods to today's problems and rarely waste time reinventing the wheel." },
    { title: "Disciplined Follow-Through", description: "They finish what others start. Their inner standard for closure is unusually high." },
    { title: "Integrity", description: "They keep their word. They do not cut corners when nobody is looking. Trust compounds around them." },
    { title: "Clear, Grounded Decision-Making", description: "They evaluate the facts, weigh the risks, and decide — without excessive drama." },
  ],
  weaknesses: [
    { title: "Resistant to Change", description: "If a system works, they resist replacing it. Innovation can feel reckless, even when it is needed." },
    { title: "Overly Cautious", description: "They can underestimate opportunities because they weigh every risk carefully. Their caution sometimes costs them upside." },
    { title: "Struggles to Express Emotion", description: "Their care is shown in action, not words. Partners and colleagues can feel emotionally underfed." },
    { title: "Judgemental of Others", description: "They hold a quiet, high standard and can be harsh on those who appear careless or undisciplined." },
    { title: "Can Be Inflexible", description: "They may keep applying yesterday's rule to a new situation that calls for a fresh approach." },
  ],
  stressTriggers: [
    "Chaotic environments with no clear structure or plan",
    "Being asked to rely on intuition alone without data",
    "Constant last-minute changes to plans they already committed to",
    "Working with unreliable people who do not keep commitments",
    "Being publicly pushed outside their area of competence",
    "Excessive small-talk or social performance demands",
    "Seeing a respected institution or process broken by carelessness",
  ],
  stressSigns: [
    "Becoming rigid and mechanical, unable to adapt",
    "Catastrophising worst-case scenarios with unusual vividness",
    "Uncharacteristic emotional outbursts or paralysis",
    "Withdrawing entirely and becoming uncommunicative",
    "Obsessing over small details while the larger picture suffers",
    "Sudden impulsive decisions that are unlike them",
  ],
  recoveryStrategies: [
    "Return to a familiar routine — sleep, meals, exercise, clear daily structure",
    "Complete one clean, concrete task that offers real progress",
    "Spend time alone to think without anyone else's input",
    "Talk to one trusted, calm person who respects their way of processing",
    "Limit new information — close the news, postpone new decisions",
  ],
  socialBattery: 30,
  relationships: {
    narrative: "ISTJs love in a deep, quiet, long-term way. They commit slowly but almost permanently, and they show love through acts of reliability — the utility bill paid on time, the dishwasher fixed, the quiet showing-up during hard seasons. Words of love are not their first language, and they can leave partners hungry for verbal warmth. The ideal partner can read the care in their actions and gently draw out the warmer words when needed.",
    offers: ["Unwavering loyalty and a partner who will never flake", "Calm, competent handling of all the practical demands of shared life", "A stable, safe home base in every season"],
    needs: ["A partner who respects structure, plans, and commitments", "Patience with their reserved emotional expression", "Shared values around honesty, responsibility, and reliability"],
    challenges: ["Can appear emotionally distant even when deeply committed", "Struggles to articulate feelings in real time during conflict", "May resist a partner's push for spontaneity or surprise"],
    compatibleWith: [
      { type: "ESFP", reason: "A warm, expressive partner who draws the ISTJ out of pure duty into more play" },
      { type: "ESTP", reason: "A lively counterpart who shares the Sensing grounding but adds adventure" },
      { type: "ISFJ", reason: "A fellow Si-dominant who understands the quiet love language of showing up" },
    ],
  },
  friendships: {
    narrative: "ISTJs are rare, long-term friends. They tend to keep the same small circle for decades, and they quietly show up through every major life event — weddings, funerals, hospital visits, moves. They do not chase new friends, but the ones they have can count on them permanently.",
    positives: ["The friend who remembers your parents' names, your birthday, your exact coffee order", "The friend who is always on time and will wait in the rain for you if needed", "The friend who offers practical help — a lift, a repair, a ride to the airport — without being asked"],
    watchOuts: ["Can be quietly judgemental of friends who seem irresponsible or flaky", "May struggle to offer the verbal reassurance a hurting friend actually needs"],
  },
  career: {
    narrative: "ISTJs thrive in structured, procedure-rich environments where accuracy, reliability, and follow-through are valued. They excel in roles with clear responsibilities, measurable standards, and stable expectations. They tend to struggle in ambiguous, fast-changing, or highly political environments where the rules keep shifting.",
    bestCareers: [
      { label: "Accountant / Auditor", icon: "bar-chart" },
      { label: "Military Officer", icon: "shield" },
      { label: "Judge", icon: "scale" },
      { label: "Civil Engineer", icon: "building" },
      { label: "Database Administrator", icon: "clipboard-list" },
      { label: "Compliance Officer", icon: "shield" },
      { label: "Logistics Manager", icon: "briefcase" },
      { label: "Financial Analyst", icon: "bar-chart" },
    ],
    leadershipStyle: ["Leads by example — works harder and more carefully than anyone they supervise", "Sets clear standards and expects everyone to meet them", "Prefers stable structures, documented processes, and predictable outcomes", "Can be slow to embrace new methods, even when change is warranted"],
    asTeammate: ["The person who actually reads the specification and holds the team to it", "Catches errors and omissions before they reach production", "Keeps their word, always — a rare gift under pressure"],
    cautionCareers: ["Volatile, improvisation-heavy startups with no clear structure", "Creative arts where ambiguity is the entire medium"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "Your twenties are the decade of proving your discipline. Build the track record — the finished degree, the shipped projects, the accumulated competence. But practice flexibility too; the world is not a closed system, and openness is a skill you can learn." },
    { phase: "In Your 30s", description: "Your competence is established; now your growth is in leadership and emotional expression. Learn to articulate appreciation out loud, delegate without over-checking, and make room for approaches different from your own. Your reliability will be multiplied through the people you lead." },
    { phase: "Midlife", description: "Your inferior Intuition function begins to surface. You may develop unexpected interest in new ideas, travel, spirituality, or imaginative work. Welcome it; it keeps you from calcifying." },
    { phase: "Mature Expression", description: "At your best, you become the respected elder whose long record of integrity speaks for itself. People come to you for judgement, and you give it carefully, without needing applause." },
  ],
  topGrowthChallenges: ["Say thank you and I appreciate you out loud — the people you rely on need to hear it", "Before you reject a new approach, ask what problem it is actually trying to solve", "Schedule flexibility deliberately; you grow by doing the occasional thing you did not plan"],
  famousPeople: [
    { name: "George H. W. Bush", role: "US President", reason: "Duty-bound, measured, long career of steady public service" },
    { name: "Emperor Meiji", role: "Emperor of Japan", reason: "Disciplined modernizer who methodically transformed Japan with structured reform" },
    { name: "Anthony Hopkins", role: "Actor", reason: "Disciplined, meticulous craftsman known for rigorous preparation and consistency" },
    { name: "Henry Ford", role: "Industrialist", reason: "Systematic, methodical builder of process and standardised production" },
    { name: "Natalie Portman", role: "Actress", reason: "Disciplined, methodical, rigorous in her craft and academic pursuits" },
    { name: "Hijikata Toshizō", role: "Shinsengumi vice-commander", reason: "Strict, dutiful, and procedurally rigorous enforcer of order" },
    { name: "Condoleezza Rice", role: "Statesman", reason: "Rigorous, accomplished, precise, long record of public service" },
    { name: "Eddard Stark", role: "Fictional (Game of Thrones)", reason: "Honourable, duty-bound, consistent to a fault" },
    { name: "Hermione Granger's more procedural moments", role: "Fictional", reason: "Rule-following diligence and relentless preparation" },
  ],
  typeComparisons: [
    {
      vsType: "ESTJ",
      sharedTraits: ["Both Si-plus-Te types", "Practical, duty-driven, highly organised", "Prefer proven systems"],
      keyDifferences: ["ISTJs prefer solo, deep, specialist work; ESTJs prefer leading visible teams", "ISTJs process internally first; ESTJs speak up and act publicly", "ISTJs maintain; ESTJs direct"],
      youMightBeThis: "If you genuinely enjoy leading teams in real time and feel energised rather than drained by managing people",
    },
    {
      vsType: "ISFJ",
      sharedTraits: ["Both Si-dominant introverts", "Devoted, reliable, service-oriented", "Quietly observant"],
      keyDifferences: ["ISTJs make decisions through Te logic; ISFJs through Fe harmony", "ISTJs prioritise efficiency; ISFJs prioritise people", "ISTJs are direct; ISFJs are gentle"],
      youMightBeThis: "If your default is to protect people's feelings and maintain harmony, not to impose logical order",
    },
  ],
  affirmations: ["My reliability is a quiet superpower — it is why people trust me.", "I can honour my standards and still make space for growth, change, and warmth.", "Saying what I feel, not just doing what I promised, deepens the love I already give."],
};
