import type { PremiumTypeData } from '../premiumTypeData';

export const ISTP: PremiumTypeData = {
  code: "ISTP",
  name: "The Craftsman",
  tagline: "Calmly troubleshooting a critical problem under intense pressure",
  accentColor: "hsl(200 35% 40%)",
  traits: ["Introverted", "Observant", "Thinking", "Perceiving"],
  famousQuote: { text: "The most reliable way to predict the future is to create it.", person: "Often attributed to builders of the ISTP mold" },
  introduction: [
    "ISTPs are the calm, competent troubleshooters of the type world. Hand them a broken engine, a failing system, or a genuine emergency, and they quiet down, find the fault, and fix it — often while everyone else is still panicking.",
    "ISTPs approach life analytically and practically. They trust what they can see, touch, and test. They are not interested in abstract theory unless it clearly cashes out in the real world, and they distrust emotional arguments that cannot point to a concrete cause.",
    "ISTPs focus on the present and on working mechanisms. They read physical systems — and often people — with unusual accuracy, but they rarely broadcast what they see. They tend to be observant, independent, resourceful, and deeply self-directed.",
    "ISTPs are usually excellent at crafts, trades, engineering, piloting, investigation, and anything that rewards calm competence under real-world conditions. Their hands and their analysis work in tight collaboration.",
    "Because ISTPs are private and often low-verbal, others may mistake them for aloof or uninterested. In reality they are simply not wired for small talk or performative enthusiasm. When they say something, they mean it — and when they show up, it is because they chose to.",
    "Others see ISTPs as cool-headed, capable, a little mysterious, and suddenly funny in a dry, unexpected way. Inside their small circle they are loyal, easy to be around, and quietly generous. They need a lot of freedom and do not bond with people who demand constant emotional performance.",
  ],
  cognitiveFunctions: {
    dominant: { name: "Introverted Thinking", abbr: "Ti", description: "Your primary mode. You reason from the inside out, building precise internal models of how things actually work. You care about logical consistency more than agreement or social comfort." },
    auxiliary: { name: "Extraverted Sensing", abbr: "Se", description: "Your support system. You are present to the physical world — attuned to movement, force, signal, detail. This is why your analytical mind produces real-world competence rather than just theory." },
    tertiary: { name: "Introverted Intuition", abbr: "Ni", description: "Developing with age. Over time you gain a quiet capacity for pattern-seeing and long-range insight. It makes you a sharper strategist once you have the experience to anchor it." },
    inferior: { name: "Extraverted Feeling", abbr: "Fe", description: "Your hidden edge and stress trigger. Group emotional dynamics are foreign territory. Under heavy stress you may become unexpectedly emotional, awkwardly hypersensitive, or fixated on being misunderstood." },
  },
  strengths: [
    { title: "Calm Under Pressure", description: "When others panic, the ISTP gets quieter and sharper. Real emergencies are often where they do their best work." },
    { title: "Hands-On Problem Solving", description: "They can take almost any physical system apart, understand it, and put it back together. Their competence is tangible." },
    { title: "Independent and Self-Directed", description: "They need very little external structure. Give them a problem and leave them alone and they will solve it." },
    { title: "Logical Precision", description: "They reason carefully and are not fooled by emotional or rhetorical framing. Their conclusions tend to hold up." },
    { title: "Adaptable and Resourceful", description: "They can improvise their way through almost anything. Limited tools, hostile conditions — they find a way." },
    { title: "Low Drama", description: "They are allergic to theatrics. Their presence steadies a team and cuts through noise." },
  ],
  weaknesses: [
    { title: "Emotionally Reserved", description: "They rarely express feelings and can leave partners and friends unsure of where they stand." },
    { title: "Restless With Routine", description: "Once a problem is solved, they lose interest. Long maintenance work can drain them." },
    { title: "Risk-Seeking", description: "Their Se pull toward intensity can take them into physical or financial risks they should think through more carefully." },
    { title: "Avoids Long-Term Commitment", description: "Decisions that lock them in — jobs, relationships, mortgages — can feel threatening to their need for freedom." },
    { title: "Can Seem Detached", description: "Their non-verbal, non-performative style can come across as cold, even when they care." },
  ],
  stressTriggers: [
    "Being forced into extensive, performative social interaction",
    "Rigid bureaucracy that prevents them from solving the actual problem",
    "Heavy emotional demands or prolonged interpersonal drama",
    "Long-term routine work with no variation or challenge",
    "Being micromanaged inside their area of real competence",
    "Loss of physical autonomy — feeling trapped or constrained",
    "Environments that punish directness and reward politics",
  ],
  stressSigns: [
    "Uncharacteristic emotional outbursts that seem to come from nowhere",
    "Sudden hypersensitivity to tone and perceived disrespect",
    "Withdrawing completely and cutting off contact",
    "Impulsive, risky behaviour — speed, spending, escape",
    "Fixating on small logical inconsistencies in an almost obsessive way",
    "Becoming unusually concerned about being liked or understood",
  ],
  recoveryStrategies: [
    "Solo time with a hands-on project — tools, a build, a repair",
    "Physical activity — riding, climbing, sport, the outdoors",
    "Get out of town for a few days without telling many people",
    "Short, unsentimental conversation with one person they trust",
    "Simplify the environment — fewer appointments, fewer messages",
  ],
  socialBattery: 30,
  relationships: {
    narrative: "ISTPs are steady, low-drama partners who are slow to commit and slow to leave. They express love through competent presence — fixing the thing, handling the crisis, showing up reliably — more than through words. They need a partner who can read action as affection and does not require constant verbal reassurance. Their risk is withdrawing when intimacy or emotional intensity gets uncomfortable, rather than working through it.",
    offers: ["Calm, competent partnership through every practical challenge", "Loyalty and reliability without drama", "A partner who respects your independence and does not crowd you"],
    needs: ["A partner who respects their need for space and autonomy", "Patience with low verbal warmth", "No manufactured drama or demand for constant emotional performance"],
    challenges: ["Can withdraw during emotional conflict rather than engage", "May struggle to express affection in words", "Tend to avoid conversations about the future of the relationship"],
    compatibleWith: [
      { type: "ESFJ", reason: "A warm, expressive partner who decodes the ISTP's quiet love and draws them out gently" },
      { type: "ENFJ", reason: "A structured, emotionally articulate counterpart who helps them name what they feel" },
      { type: "ESTJ", reason: "A decisive partner who shares the ISTP's practical groundedness and respects their autonomy" },
    ],
  },
  friendships: {
    narrative: "ISTPs are low-maintenance, high-trust friends. They may not check in weekly, but they will drop everything to help you when it counts, and will not make a big deal out of it. Their friendship is built on shared activities, mutual respect, and a refreshing absence of emotional performance.",
    positives: ["The friend who shows up in the middle of the night to help you with a real emergency", "The friend who teaches you a skill patiently and does not make you feel stupid", "The friend whose dry humour makes hard weeks survivable"],
    watchOuts: ["Can go quiet for long stretches and forget to reach out first", "May struggle to offer verbal comfort when a friend needs words, not solutions"],
  },
  career: {
    narrative: "ISTPs thrive in hands-on, problem-rich, autonomy-respecting work. They excel in trades, engineering, piloting, investigation, emergency response, and skilled craft. They struggle in heavily bureaucratic, politically noisy, or emotionally performative environments. The ideal ISTP role has real problems, real tools, real competence standards, and minimal meetings.",
    bestCareers: [
      { label: "Mechanical / Electrical Engineer", icon: "building" },
      { label: "Pilot", icon: "briefcase" },
      { label: "Paramedic / Firefighter", icon: "shield" },
      { label: "Police Detective", icon: "briefcase" },
      { label: "Carpenter / Skilled Trades", icon: "briefcase" },
      { label: "Software Engineer", icon: "building" },
      { label: "Forensic Investigator", icon: "briefcase" },
      { label: "Surgeon", icon: "briefcase" },
    ],
    leadershipStyle: ["Leads by visible competence and quiet command under pressure", "Delegates freely and trusts people to self-direct", "Avoids ceremony, long meetings, and political positioning", "Can neglect the softer dimensions of leadership — recognition, emotional support"],
    asTeammate: ["The person who stays calm while everyone else is panicking", "Finds the actual fault in the system while others theorise", "Says less and delivers more"],
    cautionCareers: ["Long desk-bound roles dominated by meetings and administration", "Sustained emotional-labour roles that require constant performative warmth"],
  },
  growthRoadmap: [
    { phase: "In Your 20s", description: "Your twenties are the decade of building real craft. Lean into the hands-on mastery, take the hard technical roles, and accumulate serious competence. But practice staying in one place long enough for depth — always leaving before the hard part costs you the top of your field." },
    { phase: "In Your 30s", description: "Now the task is integrating your expertise with the softer skills. Learn to mentor, to communicate what you know, and to be emotionally present with the people who love you. Your technical excellence needs a human frame if it is going to compound." },
    { phase: "Midlife", description: "Your inferior Feeling function begins to break through. You may find yourself unexpectedly moved by family, community, and relationships. Welcome it; it is the missing half of a complete life." },
    { phase: "Mature Expression", description: "At your best, you become the respected master craftsman whose calm, hands-on wisdom is sought by the next generation. Your quiet warmth has caught up to your long-standing competence." },
  ],
  topGrowthChallenges: ["Practice saying the warm thing out loud — your people need to hear it", "Commit to one important thing past the point where it gets boring; depth pays", "Notice when you are withdrawing to avoid feeling, and choose to stay in the room"],
  famousPeople: [
    { name: "Clint Eastwood", role: "Actor & director", reason: "Calm, laconic, competent; the classic ISTP screen presence" },
    { name: "Masutatsu Ōyama", role: "Karate master", reason: "Solitary, disciplined martial artist who tested himself through relentless physical practice" },
    { name: "Bruce Lee", role: "Martial artist", reason: "Disciplined, analytical, physically masterful, self-directed" },
    { name: "Amelia Earhart", role: "Aviator", reason: "Independent, bold, quietly competent in the air and on the ground" },
    { name: "Tom Cruise", role: "Actor", reason: "Known for doing his own stunts; physical, driven, detail-obsessed" },
    { name: "Minamoto no Yoshitsune", role: "Samurai general", reason: "Tactically brilliant, improvisational warrior with cool battlefield instincts" },
    { name: "Michael Jordan", role: "Basketball great", reason: "Competitive, present under pressure, relentless practice" },
    { name: "Indiana Jones", role: "Fictional", reason: "Competent, resourceful, calm-under-pressure adventurer" },
    { name: "James Bond", role: "Fictional", reason: "Cool-headed, analytical, physically adept, emotionally private" },
  ],
  typeComparisons: [
    {
      vsType: "ISTJ",
      sharedTraits: ["Both introverts", "Practical, grounded, observation-based", "Calm and low-drama"],
      keyDifferences: ["ISTPs are flexible and improvisational; ISTJs are structured and procedural", "ISTPs love variety; ISTJs love routine", "ISTPs open up systems; ISTJs maintain them"],
      youMightBeThis: "If you prefer clear procedures, stable schedules, and finishing a job to spec rather than improvising on the fly",
    },
    {
      vsType: "ESTP",
      sharedTraits: ["Both Se-using types", "Present-focused, hands-on, calm in emergencies", "Allergic to bureaucracy"],
      keyDifferences: ["ISTPs work solo and think before acting; ESTPs work publicly and act while thinking", "ISTPs recharge alone; ESTPs recharge in action with people", "ISTPs are quiet; ESTPs are loud"],
      youMightBeThis: "If you love being in the middle of a public, fast-moving situation and feel drained by long solo work",
    },
  ],
  affirmations: ["My calm competence is a gift — and so is the warmth I allow myself to express.", "I can stay in the room when feelings arrive; it does not diminish me.", "Commitment does not erase my freedom; it gives my freedom a destination."],
};
